### ISSUE TITLE
Panic Runtime Error

### ISSUE THREAD

**Issue by neupaneshapath** [spf13/hugo#1087]
Hugo Themes Error using Hyde-X. 

```go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7d0fb]

goroutine 1 [running]:
text/template.errRecover(0xc2081c11d8)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:100 +0xbc
github.com/spf13/hugo/hugolib.(*pager).Pages(0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/hugolib/pagination.go:55 +0x1b
reflect.Value.call(0x633c40, 0xc2081b9488, 0x1353, 0x663db0, 0x4, 0x99bc48, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x633c40, 0xc2081b9488, 0x1353, 0x99bc48, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0x633c40, 0xc2081b9488, 0x1353, 0xaa0fb8, 0xc2080d6270, 0xc20802ab9b, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalField(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0xc20802ab9b, 0x5, 0xaa0fb8, 0xc2080d6270, 0xc20802abf0, 0x1, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:478 +0x34b
text/template.(*state).evalFieldChain(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0x633c40, 0xc2081b9488, 0x56, 0xaa0fb8, 0xc2080d6270, 0xc208138250, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:449 +0x2ad
text/template.(*state).evalVariableNode(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0xc2080d6270, 0xc20802abf0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:437 +0x344
text/template.(*state).evalCommand(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0xc2080d6210, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:364 +0xa49
text/template.(*state).evalPipeline(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0xc20814ebe0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walkRange(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0xc20813e700)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:245 +0x12e
text/template.(*state).walk(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0xaa1000, 0xc20813e700)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:178 +0x2a5
text/template.(*state).walk(0xc208182c00, 0x631a80, 0xc2081961e0, 0x16, 0xaa44d0, 0xc208161c50)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc208107d80, 0xa9f700, 0xc20807f730, 0x631a80, 0xc2081961e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc2081065c0, 0xa9f700, 0xc20807f730, 0xc2081984f0, 0x10, 0x631a80, 0xc2081961e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc208110000, 0x631a80, 0xc2081961e0, 0xc2081984f0, 0x10, 0xa9f700, 0xc20807f730, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:1449 +0x210
github.com/spf13/hugo/hugolib.(*Site).render(0xc208110000, 0x6a7810, 0x8, 0x631a80, 0xc2081961e0, 0xc20807f730, 0xc208144a00, 0x6, 0x8, 0x0, ...)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:1424 +0x2c0
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc208110000, 0x6a7810, 0x8, 0x661830, 0x1, 0x631a80, 0xc2081961e0, 0xc208144a00, 0x6, 0x8, ...)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:1387 +0xdf
github.com/spf13/hugo/hugolib.(*Site).RenderHomePage(0xc208110000, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:1201 +0x178
github.com/spf13/hugo/hugolib.(*Site).Render(0xc208110000, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:395 +0x1a1
github.com/spf13/hugo/hugolib.(*Site).Build(0xc208110000, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:244 +0x84
github.com/spf13/hugo/commands.buildSite(0xc2081c1a27, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/commands/hugo.go:342 +0xd2
github.com/spf13/hugo/commands.build(0xc2081c1b5e, 0x1, 0x1)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/commands/hugo.go:254 +0x2cb
github.com/spf13/hugo/commands.server(0x98c8e0, 0xc20801e620, 0x0, 0x2)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/commands/server.go:97 +0x58a
github.com/spf13/cobra.(*Command).execute(0x98c8e0, 0xc20801e560, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/cobra/command.go:399 +0x38d
github.com/spf13/cobra.(*Command).findAndExecute(0x98bda0, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/cobra/command.go:366 +0xd4
github.com/spf13/cobra.(*Command).Execute(0x98bda0, 0x0, 0x0)
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/cobra/command.go:452 +0xab3
github.com/spf13/hugo/commands.Execute()
	/private/tmp/hugo-4EGtcz/hugo-0.13/src/github.com/spf13/hugo/commands/hugo.go:64 +0x2f
main.main()
	/private/tmp/hugo-4EGtcz/hugo-0.13/main.go:24 +0x2f
```

**Comment by bep** [comment]
Fixed in #948 -- workaround: Create some content in the section that matches Hyde-X template.
