### ISSUE TITLE
An isolated incident of Hugo panic?  (Or my CPU or RAM going bad?)

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1326]
_**Edit**: Turns out that it is the same issue as that @bep reported in "#917: Data race in Go templates" back in February 2015, where one race condition remains that is fixed in the Go 1.5 development branch and Go 1.5beta3.  Lots of interesting and useful information in this thread though.  :-)

----
----

I ran to an isolated incident where running `hugo` to generate Hugo documentation first led to a strange error, then the second time a panic, and the third time finally back to normal, all within 10 seconds:

```
foka@debian:/work/git/hugo$ hugo -s docs && cp -a docs/public/* /srv/gohugo.io/
ERROR: 2015/08/05 Error while rendering page troubleshooting/strange-eof-error.md: html/template:_default/single.html:1:0: "_default/single.html" is an incomplete or empty template

foka@debian:/work/git/hugo$ hugo -s docs && cp -a docs/public/* /srv/gohugo.io/
panic: html/template internal error: template escaping out of sync

goroutine 80 [running]:
html/template.(*Template).lookupAndEscapeTemplate(0xc20802a6c0, 0xc2088b17e0, 0x1a, 0xc2088eeab0, 0x0, 0x0)
	/usr/lib/go/src/html/template/template.go:112 +0x3a6
html/template.(*Template).ExecuteTemplate(0xc20802a6c0, 0x7f392ae1e6a0, 0xc208890150, 0xc2088b17e0, 0x1a, 0xa74dc0, 0xc208355000, 0x0, 0x0)
	/usr/lib/go/src/html/template/template.go:88 +0x54
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc20812e000, 0xa74dc0, 0xc208355000, 0xc2088b17e0, 0x1a, 0x7f392ae1e6a0, 0xc208890150, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1513 +0x210
github.com/spf13/hugo/hugolib.(*Site).render(0xc20812e000, 0xc2088b19a0, 0x1b, 0xa74dc0, 0xc208355000, 0xc208890150, 0xc2083640b0, 0x1, 0x1, 0x0, ...)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1488 +0x2bd
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc20812e000, 0xc2088b19a0, 0x1b, 0xc2088b1960, 0x18, 0xa74dc0, 0xc208355000, 0xc2083640b0, 0x1, 0x1, ...)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1439 +0xdf
github.com/spf13/hugo/hugolib.pageRenderer(0xc20812e000, 0xc2083c8660, 0xc2083c8600, 0xc2083deaa0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:949 +0x47e
created by github.com/spf13/hugo/hugolib.(*Site).RenderPages
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:907 +0x124

goroutine 1 [chan send]:
github.com/spf13/hugo/hugolib.(*Site).RenderPages(0xc20812e000, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:915 +0x1f7
github.com/spf13/hugo/hugolib.(*Site).Render(0xc20812e000, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:396 +0x153
github.com/spf13/hugo/hugolib.(*Site).Build(0xc20812e000, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:244 +0x84
github.com/spf13/hugo/commands.buildSite(0xc208c55c5f, 0x1, 0x1, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/commands/hugo.go:408 +0xd2
github.com/spf13/hugo/commands.build(0x0, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/commands/hugo.go:303 +0x2cb
github.com/spf13/hugo/commands.func·008(0xdb99c0, 0xc2080f2320, 0x0, 0x2)
	/home/foka/go/src/github.com/spf13/hugo/commands/hugo.go:54 +0x3f
github.com/spf13/cobra.(*Command).execute(0xdb99c0, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/cobra/command.go:477 +0x3d4
github.com/spf13/cobra.(*Command).Execute(0xdb99c0, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/cobra/command.go:551 +0x414
github.com/spf13/hugo/commands.Execute()
	/home/foka/go/src/github.com/spf13/hugo/commands/hugo.go:67 +0x2f
main.main()
	/home/foka/go/src/github.com/spf13/hugo/main.go:24 +0x2f

goroutine 115 [chan receive]:
github.com/spf13/hugo/hugolib.errorCollator(0xc2083c8600, 0xc2083c86c0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:958 +0x9e
created by github.com/spf13/hugo/hugolib.(*Site).RenderPages
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:912 +0x170

goroutine 113 [runnable]:
github.com/spf13/hugo/helpers.UnicodeSanitize(0xc208150c2d, 0x8, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/helpers/path.go:109 +0x4c5
github.com/spf13/hugo/helpers.MakePath(0xc208150c2d, 0x8, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/helpers/path.go:78 +0xbd
github.com/spf13/hugo/hugolib.(*Page).TargetPath(0xc208360000, 0xc2089481e0, 0xd)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/page.go:894 +0x5aa
github.com/spf13/hugo/hugolib.pageRenderer(0xc20812e000, 0xc2083c8660, 0xc2083c8600, 0xc2083deaa0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:949 +0x33e
created by github.com/spf13/hugo/hugolib.(*Site).RenderPages
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:907 +0x124

goroutine 114 [runnable]:
text/template.(*state).walk(0xc208179900, 0xa34220, 0xc2082d28b8, 0xd6, 0x7f392ae210a0, 0xc208116780)
	/usr/lib/go/src/text/template/exec.go:161
text/template.(*state).walk(0xc208179900, 0xa34220, 0xc2082d28b8, 0xd6, 0x7f392ae31be8, 0xc2080e89c0)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.(*state).walkIfOrWith(0xc208179900, 0xa, 0xa34220, 0xc2082d28b8, 0xd6, 0xc2080d8d70, 0xc2080e89c0, 0xc2080e9440)
	/usr/lib/go/src/text/template/exec.go:205 +0x33e
text/template.(*state).walk(0xc208179900, 0xa34220, 0xc2082d28b8, 0xd6, 0x7f392ae210a0, 0xc208116d00)
	/usr/lib/go/src/text/template/exec.go:172 +0x616
text/template.(*state).walk(0xc208179900, 0xa34220, 0xc2082d28b8, 0xd6, 0x7f392ae31be8, 0xc2080e88d0)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.func·001(0x8e0740, 0xc20888e530, 0x42, 0xa34220, 0xc2082d28b8, 0xd6)
	/usr/lib/go/src/text/template/exec.go:257 +0x21e
text/template.(*state).walkRange(0xc208179900, 0xa74dc0, 0xc2083ef800, 0x16, 0xc208116d80)
	/usr/lib/go/src/text/template/exec.go:266 +0x47d
text/template.(*state).walk(0xc208179900, 0xa74dc0, 0xc2083ef800, 0x16, 0x7f392ae211c0, 0xc208116d80)
	/usr/lib/go/src/text/template/exec.go:178 +0x2a5
text/template.(*state).walk(0xc208179900, 0xa74dc0, 0xc2083ef800, 0x16, 0x7f392ae31be8, 0xc2080e8690)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc2081165c0, 0x7f392ae1e6a0, 0xc20839fb90, 0xa74dc0, 0xc2083ef800, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc20802a6c0, 0x7f392ae1e6a0, 0xc20839fb90, 0xc2087ebaa0, 0x12, 0xa74dc0, 0xc2083ef800, 0x0, 0x0)
	/usr/lib/go/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/tpl.ExecuteTemplate(0xa74dc0, 0xc2083ef800, 0xc20839fb90, 0xc2087eba80, 0x2, 0x2)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:118 +0x1d6
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0xa74dc0, 0xc2083ef800, 0xc2087eba80, 0x2, 0x2, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:135 +0xaa
github.com/spf13/hugo/tpl.Partial(0xc2081d885c, 0x9, 0xc2087e96d0, 0x1, 0x1, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:104 +0x260
reflect.Value.call(0x974c80, 0xbc77c8, 0x13, 0xa809c0, 0x4, 0xc208553890, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x974c80, 0xbc77c8, 0x13, 0xc208553860, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc208179600, 0xa74dc0, 0xc2083ef800, 0x16, 0x974c80, 0xbc77c8, 0x13, 0x7f392ae31c30, 0xc2081e03c0, 0xc2081d8853, ...)
	/usr/lib/go/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalFunction(0xc208179600, 0xa74dc0, 0xc2083ef800, 0x16, 0xc2081e03f0, 0x7f392ae31c30, 0xc2081e03c0, 0xc2081160c0, 0x3, 0x4, ...)
	/usr/lib/go/src/text/template/exec.go:459 +0x33b
text/template.(*state).evalCommand(0xc208179600, 0xa74dc0, 0xc2083ef800, 0x16, 0xc2081e03c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/text/template/exec.go:359 +0x210
text/template.(*state).evalPipeline(0xc208179600, 0xa74dc0, 0xc2083ef800, 0x16, 0xc20802e5f0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walk(0xc208179600, 0xa74dc0, 0xc2083ef800, 0x16, 0x7f392ae1e310, 0xc2081e0420)
	/usr/lib/go/src/text/template/exec.go:167 +0x145
text/template.(*state).walk(0xc208179600, 0xa74dc0, 0xc2083ef800, 0x16, 0x7f392ae31be8, 0xc2081e0060)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc2081a0180, 0x7f392ae1e6a0, 0xc20839fc70, 0xa74dc0, 0xc2083ef800, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc20802a6c0, 0x7f392ae1e6a0, 0xc20839fc70, 0xc2087eb640, 0x14, 0xa74dc0, 0xc2083ef800, 0x0, 0x0)
	/usr/lib/go/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/tpl.ExecuteTemplate(0xa74dc0, 0xc2083ef800, 0xc20839fc70, 0xc2087eb620, 0x2, 0x2)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:118 +0x1d6
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0xa74dc0, 0xc2083ef800, 0xc2087eb620, 0x2, 0x2, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:135 +0xaa
github.com/spf13/hugo/tpl.Partial(0xc2080808cc, 0xb, 0xc2087e9440, 0x1, 0x1, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:104 +0x260
reflect.Value.call(0x974c80, 0xbc77c8, 0x13, 0xa809c0, 0x4, 0xc2085534a0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x974c80, 0xbc77c8, 0x13, 0xc208553470, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc2081793c0, 0xa74dc0, 0xc2083ef800, 0x16, 0x974c80, 0xbc77c8, 0x13, 0x7f392ae31c30, 0xc20819db00, 0xc2080808c3, ...)
	/usr/lib/go/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalFunction(0xc2081793c0, 0xa74dc0, 0xc2083ef800, 0x16, 0xc20819db30, 0x7f392ae31c30, 0xc20819db00, 0xc20816f740, 0x3, 0x4, ...)
	/usr/lib/go/src/text/template/exec.go:459 +0x33b
text/template.(*state).evalCommand(0xc2081793c0, 0xa74dc0, 0xc2083ef800, 0x16, 0xc20819db00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/text/template/exec.go:359 +0x210
text/template.(*state).evalPipeline(0xc2081793c0, 0xa74dc0, 0xc2083ef800, 0x16, 0xc20817b450, 0x0, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walk(0xc2081793c0, 0xa74dc0, 0xc2083ef800, 0x16, 0x7f392ae1e310, 0xc2081bcbd0)
	/usr/lib/go/src/text/template/exec.go:167 +0x145
text/template.(*state).walk(0xc2081793c0, 0xa74dc0, 0xc2083ef800, 0x16, 0x7f392ae31be8, 0xc20819dad0)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc2081b6540, 0x7f392ae1e6a0, 0xc20839fc00, 0xa74dc0, 0xc2083ef800, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc20802a6c0, 0x7f392ae1e6a0, 0xc20839fc00, 0xc2087eb3a0, 0x14, 0xa74dc0, 0xc2083ef800, 0x0, 0x0)
	/usr/lib/go/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc20812e000, 0xa74dc0, 0xc2083ef800, 0xc2087eb3a0, 0x14, 0x7f392ae1e6a0, 0xc20839fc00, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1513 +0x210
github.com/spf13/hugo/hugolib.(*Site).render(0xc20812e000, 0xc2087eb5e0, 0x16, 0xa74dc0, 0xc2083ef800, 0xc20839fc00, 0xc2082d2100, 0x5, 0x8, 0x0, ...)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1488 +0x2bd
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc20812e000, 0xc2087eb5e0, 0x16, 0xc2087eb5a0, 0x13, 0xa74dc0, 0xc2083ef800, 0xc2082d2100, 0x5, 0x8, ...)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1439 +0xdf
github.com/spf13/hugo/hugolib.pageRenderer(0xc20812e000, 0xc2083c8660, 0xc2083c8600, 0xc2083deaa0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:949 +0x47e
created by github.com/spf13/hugo/hugolib.(*Site).RenderPages
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:907 +0x124

goroutine 79 [runnable]:
fmt.(*fmt).init(0xc2082f8058, 0xc2082f8010)
	/usr/lib/go/src/fmt/format.go:71
fmt.newPrinter(0xc2080d9040)
	/usr/lib/go/src/fmt/print.go:136 +0x96
fmt.Fprint(0x7f392ae1e6a0, 0xc208a68310, 0xc208614470, 0x1, 0x1, 0x8ddf01, 0x0, 0x0)
	/usr/lib/go/src/fmt/print.go:221 +0x34
text/template.(*state).printValue(0xc20816f400, 0x7f392ae1e310, 0xc2080e9290, 0x8e1140, 0xc20880ff38, 0x58)
	/usr/lib/go/src/text/template/exec.go:779 +0x2d8
text/template.(*state).walk(0xc20816f400, 0xa34220, 0xc2082d2738, 0xd6, 0x7f392ae1e310, 0xc2080e9290)
	/usr/lib/go/src/text/template/exec.go:169 +0x1e9
text/template.(*state).walk(0xc20816f400, 0xa34220, 0xc2082d2738, 0xd6, 0x7f392ae31be8, 0xc2080e9080)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.func·001(0x8e0740, 0xc208b04a50, 0x42, 0xa34220, 0xc2082d2738, 0xd6)
	/usr/lib/go/src/text/template/exec.go:257 +0x21e
text/template.(*state).walkRange(0xc20816f400, 0xa34220, 0xc2082d28d8, 0xd6, 0xc208116c40)
	/usr/lib/go/src/text/template/exec.go:266 +0x47d
text/template.(*state).walk(0xc20816f400, 0xa34220, 0xc2082d28d8, 0xd6, 0x7f392ae211c0, 0xc208116c40)
	/usr/lib/go/src/text/template/exec.go:178 +0x2a5
text/template.(*state).walk(0xc20816f400, 0xa34220, 0xc2082d28d8, 0xd6, 0x7f392ae31be8, 0xc2080e89c0)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.(*state).walkIfOrWith(0xc20816f400, 0xa, 0xa34220, 0xc2082d28d8, 0xd6, 0xc2080d8d70, 0xc2080e89c0, 0xc2080e9440)
	/usr/lib/go/src/text/template/exec.go:205 +0x33e
text/template.(*state).walk(0xc20816f400, 0xa34220, 0xc2082d28d8, 0xd6, 0x7f392ae210a0, 0xc208116d00)
	/usr/lib/go/src/text/template/exec.go:172 +0x616
text/template.(*state).walk(0xc20816f400, 0xa34220, 0xc2082d28d8, 0xd6, 0x7f392ae31be8, 0xc2080e88d0)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.func·001(0x8e0740, 0xc208b043f8, 0x42, 0xa34220, 0xc2082d28d8, 0xd6)
	/usr/lib/go/src/text/template/exec.go:257 +0x21e
text/template.(*state).walkRange(0xc20816f400, 0xa74dc0, 0xc208360c00, 0x16, 0xc208116d80)
	/usr/lib/go/src/text/template/exec.go:266 +0x47d
text/template.(*state).walk(0xc20816f400, 0xa74dc0, 0xc208360c00, 0x16, 0x7f392ae211c0, 0xc208116d80)
	/usr/lib/go/src/text/template/exec.go:178 +0x2a5
text/template.(*state).walk(0xc20816f400, 0xa74dc0, 0xc208360c00, 0x16, 0x7f392ae31be8, 0xc2080e8690)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc2081165c0, 0x7f392ae1e6a0, 0xc208a68310, 0xa74dc0, 0xc208360c00, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc20802a6c0, 0x7f392ae1e6a0, 0xc208a68310, 0xc208a72500, 0x12, 0xa74dc0, 0xc208360c00, 0x0, 0x0)
	/usr/lib/go/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/tpl.ExecuteTemplate(0xa74dc0, 0xc208360c00, 0xc208a68310, 0xc208a724e0, 0x2, 0x2)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:118 +0x1d6
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0xa74dc0, 0xc208360c00, 0xc208a724e0, 0x2, 0x2, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:135 +0xaa
github.com/spf13/hugo/tpl.Partial(0xc2081d885c, 0x9, 0xc2080299a0, 0x1, 0x1, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:104 +0x260
reflect.Value.call(0x974c80, 0xbc77c8, 0x13, 0xa809c0, 0x4, 0xc208bc6480, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x974c80, 0xbc77c8, 0x13, 0xc208bc6450, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc20816e780, 0xa74dc0, 0xc208360c00, 0x16, 0x974c80, 0xbc77c8, 0x13, 0x7f392ae31c30, 0xc2081e03c0, 0xc2081d8853, ...)
	/usr/lib/go/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalFunction(0xc20816e780, 0xa74dc0, 0xc208360c00, 0x16, 0xc2081e03f0, 0x7f392ae31c30, 0xc2081e03c0, 0xc2081160c0, 0x3, 0x4, ...)
	/usr/lib/go/src/text/template/exec.go:459 +0x33b
text/template.(*state).evalCommand(0xc20816e780, 0xa74dc0, 0xc208360c00, 0x16, 0xc2081e03c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/text/template/exec.go:359 +0x210
text/template.(*state).evalPipeline(0xc20816e780, 0xa74dc0, 0xc208360c00, 0x16, 0xc20802e5f0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walk(0xc20816e780, 0xa74dc0, 0xc208360c00, 0x16, 0x7f392ae1e310, 0xc2081e0420)
	/usr/lib/go/src/text/template/exec.go:167 +0x145
text/template.(*state).walk(0xc20816e780, 0xa74dc0, 0xc208360c00, 0x16, 0x7f392ae31be8, 0xc2081e0060)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc2081a0180, 0x7f392ae1e6a0, 0xc208a68070, 0xa74dc0, 0xc208360c00, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc20802a6c0, 0x7f392ae1e6a0, 0xc208a68070, 0xc208a720a0, 0x14, 0xa74dc0, 0xc208360c00, 0x0, 0x0)
	/usr/lib/go/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/tpl.ExecuteTemplate(0xa74dc0, 0xc208360c00, 0xc208a68070, 0xc208a72080, 0x2, 0x2)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:118 +0x1d6
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0xa74dc0, 0xc208360c00, 0xc208a72080, 0x2, 0x2, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:135 +0xaa
github.com/spf13/hugo/tpl.Partial(0xc2080808cc, 0xb, 0xc208028c50, 0x1, 0x1, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/tpl/template.go:104 +0x260
reflect.Value.call(0x974c80, 0xbc77c8, 0x13, 0xa809c0, 0x4, 0xc208bc6060, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x974c80, 0xbc77c8, 0x13, 0xc208bc6030, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc20816e380, 0xa74dc0, 0xc208360c00, 0x16, 0x974c80, 0xbc77c8, 0x13, 0x7f392ae31c30, 0xc20819db00, 0xc2080808c3, ...)
	/usr/lib/go/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalFunction(0xc20816e380, 0xa74dc0, 0xc208360c00, 0x16, 0xc20819db30, 0x7f392ae31c30, 0xc20819db00, 0xc20816f740, 0x3, 0x4, ...)
	/usr/lib/go/src/text/template/exec.go:459 +0x33b
text/template.(*state).evalCommand(0xc20816e380, 0xa74dc0, 0xc208360c00, 0x16, 0xc20819db00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/text/template/exec.go:359 +0x210
text/template.(*state).evalPipeline(0xc20816e380, 0xa74dc0, 0xc208360c00, 0x16, 0xc20817b450, 0x0, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walk(0xc20816e380, 0xa74dc0, 0xc208360c00, 0x16, 0x7f392ae1e310, 0xc2081bcbd0)
	/usr/lib/go/src/text/template/exec.go:167 +0x145
text/template.(*state).walk(0xc20816e380, 0xa74dc0, 0xc208360c00, 0x16, 0x7f392ae31be8, 0xc20819dad0)
	/usr/lib/go/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc2081b6540, 0x7f392ae1e6a0, 0xc208a68000, 0xa74dc0, 0xc208360c00, 0x0, 0x0)
	/usr/lib/go/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc20802a6c0, 0x7f392ae1e6a0, 0xc208a68000, 0xc208a70100, 0x14, 0xa74dc0, 0xc208360c00, 0x0, 0x0)
	/usr/lib/go/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc20812e000, 0xa74dc0, 0xc208360c00, 0xc208a70100, 0x14, 0x7f392ae1e6a0, 0xc208a68000, 0x0, 0x0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1513 +0x210
github.com/spf13/hugo/hugolib.(*Site).render(0xc20812e000, 0xc208a72040, 0x15, 0xa74dc0, 0xc208360c00, 0xc208a68000, 0xc208107c80, 0x5, 0x8, 0x0, ...)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1488 +0x2bd
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc20812e000, 0xc208a72040, 0x15, 0xc208a702c0, 0x12, 0xa74dc0, 0xc208360c00, 0xc208107c80, 0x5, 0x8, ...)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:1439 +0xdf
github.com/spf13/hugo/hugolib.pageRenderer(0xc20812e000, 0xc2083c8660, 0xc2083c8600, 0xc2083deaa0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:949 +0x47e
created by github.com/spf13/hugo/hugolib.(*Site).RenderPages
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:907 +0x124

foka@debian:/work/git/hugo$ hugo -s docs && cp -a docs/public/* /srv/gohugo.io/
0 draft content
0 future content 
141 pages created
0 paginator pages created
23 tags created
0 groups created
in 507 ms

foka@debian:/work/git/hugo$ 
```

Note, however that when I am unable to reproduce this problem even if I were to run the same command 100 times in a row:

```
$ for i in `seq 1 100`; do hugo -s docs && cp -a docs/public/* /srv/gohugo.io/; done
```

Oh wait, I did get 1 error out of 100 runs, but no panic:

```
ERROR: 2015/08/05 template: partials/footer.html:33:16: executing "partials/footer.html" at <{{template "partials...>: template "partials/analytics.html" not defined in partials/footer.html
```

Could it be a race condition somewhere?  Or just that my CPU or RAM is going bad?  :-)

Thanks!

**Comment by tatsushid** [comment]
I think there could be a race condition in hugo. I built hugo with `-race` option like

```
go build -race -o hugo main.go
```

and tried to build my site. It detects a race and showed its stack traces.

**Comment by spf13** [comment]
Quite possible it's in hugo. What version of Go are you using?

**Comment by tatsushid** [comment]
In my case, I used `go version go1.4.2 darwin/amd64` and the tip of the repository. I also tried to build the official document by hugo with `-race` option and it detected a race condition too but the stack traces were different from @anthonyfok case.

**Comment by bep** [comment]
Most likely this:

https://github.com/spf13/hugo/issues/917

It is fixed in Go 1.5 beta3, so that could be worth trying.

**Comment by tatsushid** [comment]
@spf13, I understand why you asked what Go version we use. In Go 1.5, there is no race at building the official document. It fixed at https://github.com/golang/go/commit/ebe733cb40c49148b2fe53d27ce9b1f76993591e.

**Comment by anthonyfok** [comment]
Thank you all for the really useful information, @tatsushid, @spf13 and @bep.

I am running Go 1.4.2:

```
$ go version
go version go1.4.2 linux/amd64
```

And I am really glad it is fixed for the upcoming Go 1.5.  :-)
(And Hugo is not buggy!  Yay!)

**Comment by bep** [comment]
I you're above average interested in nerdy stuff, this is recommended:

https://www.youtube.com/watch?v=a9xrxRsIbSU

Dmitry Vyukov wrote the race detector in Go. An interesting note is: There are no false positives, but there can be false negatives. So you may have to run the Hugo build several times.

In 1.5beta3, the Hugo Theme Site, with all its demo sites, runs without race reports.

**Comment by anthonyfok** [comment]
:+1:
