### ISSUE TITLE
mkdir fails intermittently

### ISSUE THREAD

**Issue by SvenDowideit** [spf13/hugo#1754]
We have hugo being run in a container, as a jenkins job, and every now and then, it fails with 

```
FATAL: 2016/01/04 mkdir /docs/public/engine/userguide/networking: no such file or directory
```

for eg, see https://jenkins.dockerproject.org/job/docs-compose-pr/186/console

when I hit rebuild, hugo succeeds.

I can't reproduce it locally, or intentionally - so I'm contemplating running the builds with the following change:

```
diff --git a/commands/new.go b/commands/new.go
index 8c2e485..4a6f46f 100644
--- a/commands/new.go
+++ b/commands/new.go
@@ -18,6 +18,7 @@ import (
        "errors"
        "os"
        "path/filepath"
+       "runtime"
        "strings"
        "time"

@@ -243,7 +244,12 @@ func mkdir(x ...string) {

        err := os.MkdirAll(p, 0777) // before umask
        if err != nil {
-               jww.FATAL.Fatalln(err)
+               // jww.FATAL.Fatalln(err)
+               // Tell me where the mkdir is failing.
+               buf := make([]byte, 1<<16)
+               stackSize := runtime.Stack(buf, true)
+               jww.FATAL.Fatalln(buf[0:stackSize])
        }
 }
```

is there a better way to figure out what's going on?

**Comment by anthonyfok** [comment]
Just a quick note: I don't think it is in `commands/new.go`.  If I understand correctly, the code inside `commands/new.go` only affects the `hugo new` subcommands like `hugo new post/hello-again.md`, `hugo new site`, and `hugo new theme`.  Since you are running `hugo` itself to render the website, and writing to a `public` directory, I think it is happening elsewhere.

As to why it is happening, my uneducated guess is a possible race condition where mkdir tries to create the /docs/public/engine/userguide/networking directory when the parent /docs/public/engine/userguide directory does not yet exist?  And it would most likely be a place where os.Mkdir() rather than os.MkdirAll() is used.

But how?  I suppose if such a race condition were to exist, it would have been caught by now...  But again, I am just guessing wildly, hehe.

**Comment by SvenDowideit** [comment]
yeah, that's the same conclusion i made.

except for the `mkdir` is used only by `commands/new` - if i grok right, it can be used by all the files that are in `package commands` (not that this has helped me find it)

today, I'm thinking of modding `jww` to throw a stack trace when `FATAL` for more brute force - my reproduction setup hasn't reproduced it despite running all nite

**Comment by bep** [comment]
My best guess would be to put a panic here:

https://github.com/spf13/afero/blob/e042b5f805207f2a05fe51c1d12dea7ac75968b4/util.go#L49

**Comment by thaJeztah** [comment]
ping @SvenDowideit have you looked further into this? It's becoming quite an issue for the docs CI :cry:

**Comment by SvenDowideit** [comment]
no, but I am planning on working on it more today.

**Comment by SvenDowideit** [comment]
oh wonderful - so I really want to replace all uses of `log.Fatal*` with `log.Panic*`. (for all packages that hugo uses?)

**Comment by SvenDowideit** [comment]
I've added a `sed` script to my build Dockerfile that converts all `log.Fatal` calls to `log.Panic`, in all the deps. 

we'll see if it happens again :/.

**Comment by SvenDowideit** [comment]
mmm, very odd.

so the stack trace confirms aht @bep suggested:

```
  9 2016/01/18 22:39:37 mkdir /docs/public/engine/userguide/storagedriver/images/: no such file or directory
 10 panic: mkdir /docs/public/engine/userguide/storagedriver/images/: no such file or directory
 11 
 12 
 13 goroutine 59 [running]:
 14 log.Panicln(0xc820030c00, 0x1, 0x1)
 15     /usr/local/go/src/log/log.go:334 +0xc1
 16 github.com/spf13/afero.WriteReader(0x7f2d1e160778, 0xfb3ef8, 0xc8220059a0, 0x42, 0x7f2d1e162d28, 0xc820224940, 0x7f2d1e1620f8, 0xc822274480)
 17     /go/src/github.com/spf13/afero/util.go:49 +0x353
 18 github.com/spf13/hugo/helpers.WriteToDisk(0xc8220059a0, 0x42, 0x7f2d1e162d28, 0xc820224940, 0x7f2d1e160778, 0xfb3ef8, 0x0, 0x0)
 19     /go/src/github.com/spf13/hugo/helpers/path.go:438 +0x64
 20 github.com/spf13/hugo/target.(*Filesystem).Publish(0xc821c1a720, 0xc82021fa9e, 0x35, 0x7f2d1e162d28, 0xc820224940, 0x0, 0x0)
 21     /go/src/github.com/spf13/hugo/target/file.go:52 +0xc0
 22 github.com/spf13/hugo/hugolib.(*Site).WriteDestFile(0xc8200e4000, 0xc82021fa9e, 0x35, 0x7f2d1e162d28, 0xc820224940, 0x0, 0x0)
 23     /go/src/github.com/spf13/hugo/hugolib/site.go:1798 +0x1ee
 24 github.com/spf13/hugo/hugolib.defaultHandler.FileConvert(0x0, 0x0, 0x0, 0xc820146d90, 0xc8200e4000, 0x0, 0x0, 0x0, 0x0)
 25     /go/src/github.com/spf13/hugo/hugolib/handler_file.go:42 +0x83                                                                                                                                                                                                         
 26 github.com/spf13/hugo/hugolib.(*defaultHandler).FileConvert(0xc820157be0, 0xc820146d90, 0xc8200e4000, 0x0, 0x0, 0x0, 0x0)
 27     <autogenerated>:99 +0xce
 28 github.com/spf13/hugo/hugolib.(*MetaHandle).Convert(0xc821fdea20, 0xb886c0, 0xc820146d90, 0xc8200e4000, 0xc820928d20)
 29     /go/src/github.com/spf13/hugo/hugolib/handler_meta.go:62 +0x8e
 30 github.com/spf13/hugo/hugolib.fileConverter(0xc8200e4000, 0xc820928de0, 0xc820928d20, 0xc820ab8f90)
 31     /go/src/github.com/spf13/hugo/hugolib/site.go:807 +0x107
 32 created by github.com/spf13/hugo/hugolib.(*Site).CreatePages
 33     /go/src/github.com/spf13/hugo/hugolib/site.go:740 +0x5f8
```

but its pretty odd. we're running in a non-readonly container, as root, and MkdirAll should make all the parents too.

shaking stick in other direction.

**Comment by bep** [comment]
@SvenDowideit is this still an issue?

**Comment by SvenDowideit** [comment]
it did happen once last week with hugo 0.16 - but its pretty rare now.

**Comment by AkihiroSuda** [comment]
@SvenDowideit 
I'm interested in trying to reproduce the issue.
Which version of docker/kernel/aufs(?) were you using at that time?

**Comment by bep** [comment]
FYI I changed the log.Fatal in Afero to log.Panic yesterday.

**Comment by bep** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least four months.

The resources of the Hugo team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still valuable, please open a proposal at https://discuss.gohugo.io/.

This issue will automatically be closed in four months if no further activity occurs. Thank you for all your contributions.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
