### ISSUE TITLE
Scratch: Concurrent map read and map write

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2005]
I have a hard time wrapping my head around how this happens; git this one time testing the future-imperfect theme.
```
fatal error: concurrent map read and map write

goroutine 234 [running]:
runtime.throw(0x915ac0, 0x21)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc822889070 sp=0xc822889058
runtime.mapaccess1_faststr(0x663fe0, 0xc8231054d0, 0xc821f61052, 0x8, 0xc822830840)
	/usr/local/go/src/runtime/hashmap_fast.go:202 +0x5b fp=0xc8228890d0 sp=0xc822889070
github.com/spf13/hugo/hugolib.(*Scratch).Get(0xc822069f08, 0xc821f61052, 0x8, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/scratch.go:68 +0x5a fp=0xc822889110 sp=0xc8228890d0
runtime.call64(0xc82283a1c0, 0x7db380, 0xc822620d80, 0x1800000028)
	/usr/local/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc822889158 sp=0xc822889110
reflect.Value.call(0x7db2c0, 0xc822069f08, 0x613, 0x861d20, 0x4, 0xc8237b2680, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc8228894a8 sp=0xc822889158
reflect.Value.Call(0x7db2c0, 0xc822069f08, 0x613, 0xc8237b2680, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc822889508 sp=0xc8228894a8
text/template.(*state).evalCall(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0x7db2c0, 0xc822069f08, 0x613, 0x1a1cec0, 0xc82203c4e0, 0xc82201a94a, ...)
	/usr/local/go/src/text/template/exec.go:641 +0xb39 fp=0xc822889750 sp=0xc822889508
text/template.(*state).evalField(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0xc82201a94a, 0x3, 0x1a1cec0, 0xc82203c4e0, 0xc8220385c0, 0x2, ...)
	/usr/local/go/src/text/template/exec.go:534 +0x350 fp=0xc822889aa0 sp=0xc822889750
text/template.(*state).evalFieldChain(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0x7db2c0, 0xc821ee62e8, 0x96, 0x1a1cec0, 0xc82203c4e0, 0xc82203c4c0, ...)
	/usr/local/go/src/text/template/exec.go:505 +0x29d fp=0xc822889b58 sp=0xc822889aa0
text/template.(*state).evalVariableNode(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0xc82203c4e0, 0xc8220385c0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:493 +0x349 fp=0xc822889c68 sp=0xc822889b58
text/template.(*state).evalCommand(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0xc82203c450, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:417 +0x9d0 fp=0xc822889d90 sp=0xc822889c68
text/template.(*state).evalPipeline(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0xc822034780, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:385 +0x180 fp=0xc822889f28 sp=0xc822889d90
text/template.(*state).evalArg(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0x0, 0x0, 0x1a1cc80, 0xc822034780, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:710 +0x43e fp=0xc82288a090 sp=0xc822889f28
text/template.(*state).evalChainNode(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0xc8220369c0, 0xc8220385e0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:481 +0x281 fp=0xc82288a1c0 sp=0xc82288a090
text/template.(*state).evalCommand(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0xc82203c420, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:409 +0x31c fp=0xc82288a2e8 sp=0xc82288a1c0
text/template.(*state).evalPipeline(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0xc822034730, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:385 +0x180 fp=0xc82288a480 sp=0xc82288a2e8
text/template.(*state).walk(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0x1a08958, 0xc82203c510)
	/usr/local/go/src/text/template/exec.go:215 +0x135 fp=0xc82288a5c8 sp=0xc82288a480
text/template.(*state).walk(0xc82288a808, 0x857be0, 0xc820377400, 0x16, 0x1a45680, 0xc822019650)
	/usr/local/go/src/text/template/exec.go:223 +0x6a1 fp=0xc82288a710 sp=0xc82288a5c8
text/template.(*Template).Execute(0xc822036280, 0x1a0cc90, 0xc8238e7c00, 0x857be0, 0xc820377400, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:178 +0x2a7 fp=0xc82288a850 sp=0xc82288a710
html/template.(*Template).Execute(0xc8220195f0, 0x1a0cc90, 0xc8238e7c00, 0x857be0, 0xc820377400, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:104 +0x9a fp=0xc82288a8a0 sp=0xc82288a850
github.com/spf13/hugo/tpl.executeTemplate(0x857be0, 0xc820377400, 0x1a0cc90, 0xc8238e7c00, 0xc8221ed600, 0x4, 0x4)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/template.go:129 +0x196 fp=0xc82288aa28 sp=0xc82288a8a0
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0x857be0, 0xc820377400, 0xc8221ed600, 0x4, 0x4, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/template.go:146 +0xdf fp=0xc82288aac0 sp=0xc82288aa28
github.com/spf13/hugo/hugolib.(*Page).Render(0xc820377400, 0xc822297b50, 0x1, 0x1, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/page.go:800 +0x126 fp=0xc82288ab78 sp=0xc82288aac0
runtime.call64(0xc822749a00, 0x858330, 0xc822620690, 0x2000000030)
	/usr/local/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc82288abc0 sp=0xc82288ab78
reflect.Value.call(0x857be0, 0xc820377400, 0x9213, 0x861d20, 0x4, 0xc820b6dc00, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc82288af10 sp=0xc82288abc0
reflect.Value.Call(0x857be0, 0xc820377400, 0x9213, 0xc820b6dbc0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc82288af70 sp=0xc82288af10
text/template.(*state).evalCall(0xc82288bce8, 0x857be0, 0xc820377400, 0x16, 0x857be0, 0xc820377400, 0x9213, 0x1a08910, 0xc8201afad0, 0xc8201e361f, ...)
	/usr/local/go/src/text/template/exec.go:641 +0xb39 fp=0xc82288b1b8 sp=0xc82288af70
text/template.(*state).evalField(0xc82288bce8, 0x857be0, 0xc820377400, 0x16, 0xc8201e361f, 0x6, 0x1a08910, 0xc8201afad0, 0xc82022ede0, 0x2, ...)
	/usr/local/go/src/text/template/exec.go:534 +0x350 fp=0xc82288b508 sp=0xc82288b1b8
text/template.(*state).evalFieldChain(0xc82288bce8, 0x857be0, 0xc820377400, 0x16, 0x857be0, 0xc820377400, 0x16, 0x1a08910, 0xc8201afad0, 0xc820175bf0, ...)
	/usr/local/go/src/text/template/exec.go:505 +0x29d fp=0xc82288b5c0 sp=0xc82288b508
text/template.(*state).evalFieldNode(0xc82288bce8, 0x857be0, 0xc820377400, 0x16, 0xc8201afad0, 0xc82022ede0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:469 +0x1e2 fp=0xc82288b6a0 sp=0xc82288b5c0
text/template.(*state).evalCommand(0xc82288bce8, 0x857be0, 0xc820377400, 0x16, 0xc8201afaa0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:407 +0xa91 fp=0xc82288b7c8 sp=0xc82288b6a0
text/template.(*state).evalPipeline(0xc82288bce8, 0x857be0, 0xc820377400, 0x16, 0xc82019d220, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:385 +0x180 fp=0xc82288b960 sp=0xc82288b7c8
text/template.(*state).walk(0xc82288bce8, 0x857be0, 0xc820377400, 0x16, 0x1a08958, 0xc8201afb00)
	/usr/local/go/src/text/template/exec.go:215 +0x135 fp=0xc82288baa8 sp=0xc82288b960
text/template.(*state).walk(0xc82288bce8, 0x857be0, 0xc820377400, 0x16, 0x1a45680, 0xc8201af9e0)
	/usr/local/go/src/text/template/exec.go:223 +0x6a1 fp=0xc82288bbf0 sp=0xc82288baa8
text/template.(*Template).Execute(0xc82202a580, 0x1a0cc90, 0xc823546770, 0x857be0, 0xc820377400, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:178 +0x2a7 fp=0xc82288bd30 sp=0xc82288bbf0
html/template.(*Template).Execute(0xc8201af950, 0x1a0cc90, 0xc823546770, 0x857be0, 0xc820377400, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:104 +0x9a fp=0xc82288bd80 sp=0xc82288bd30
github.com/spf13/hugo/tpl.executeTemplate(0x857be0, 0xc820377400, 0x1a0cc90, 0xc823546770, 0xc8221ed5c0, 0x4, 0x4)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/template.go:129 +0x196 fp=0xc82288bf08 sp=0xc82288bd80
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0x857be0, 0xc820377400, 0xc8221ed5c0, 0x4, 0x4, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/tpl/template.go:146 +0xdf fp=0xc82288bfa0 sp=0xc82288bf08
github.com/spf13/hugo/hugolib.(*Page).Render(0xc820377400, 0xc822297ad0, 0x1, 0x1, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/page.go:800 +0x126 fp=0xc82288c058 sp=0xc82288bfa0
runtime.call64(0xc822749a00, 0x858330, 0xc822620630, 0x2000000030)
	/usr/local/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc82288c0a0 sp=0xc82288c058
reflect.Value.call(0x857be0, 0xc820377400, 0x9213, 0x861d20, 0x4, 0xc820b6daa0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d fp=0xc82288c3f0 sp=0xc82288c0a0
reflect.Value.Call(0x857be0, 0xc820377400, 0x9213, 0xc820b6da60, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1 fp=0xc82288c450 sp=0xc82288c3f0
text/template.(*state).evalCall(0xc82288d700, 0x857be0, 0xc82240ca50, 0x196, 0x857be0, 0xc820377400, 0x9213, 0x1a08910, 0xc821fcda10, 0xc8201b1364, ...)
	/usr/local/go/src/text/template/exec.go:641 +0xb39 fp=0xc82288c698 sp=0xc82288c450
text/template.(*state).evalField(0xc82288d700, 0x857be0, 0xc82240ca50, 0x196, 0xc8201b1364, 0x6, 0x1a08910, 0xc821fcda10, 0xc82031e360, 0x2, ...)
	/usr/local/go/src/text/template/exec.go:534 +0x350 fp=0xc82288c9e8 sp=0xc82288c698
text/template.(*state).evalFieldChain(0xc82288d700, 0x857be0, 0xc82240ca50, 0x196, 0x857be0, 0xc82240ca50, 0x196, 0x1a08910, 0xc821fcda10, 0xc821faf940, ...)
	/usr/local/go/src/text/template/exec.go:505 +0x29d fp=0xc82288caa0 sp=0xc82288c9e8
text/template.(*state).evalFieldNode(0xc82288d700, 0x857be0, 0xc82240ca50, 0x196, 0xc821fcda10, 0xc82031e360, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:469 +0x1e2 fp=0xc82288cb80 sp=0xc82288caa0
text/template.(*state).evalCommand(0xc82288d700, 0x857be0, 0xc82240ca50, 0x196, 0xc821fcd9e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/text/template/exec.go:407 +0xa91 fp=0xc82288cca8 sp=0xc82288cb80
text/template.(*state).evalPipeline(0xc82288d700, 0x857be0, 0xc82240ca50, 0x196, 0xc821fc9630, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:385 +0x180 fp=0xc82288ce40 sp=0xc82288cca8
text/template.(*state).walk(0xc82288d700, 0x857be0, 0xc82240ca50, 0x196, 0x1a08958, 0xc821fcda40)
	/usr/local/go/src/text/template/exec.go:215 +0x135 fp=0xc82288cf88 sp=0xc82288ce40
text/template.(*state).walk(0xc82288d700, 0x857be0, 0xc82240ca50, 0x196, 0x1a45680, 0xc821fcd980)
	/usr/local/go/src/text/template/exec.go:223 +0x6a1 fp=0xc82288d0d0 sp=0xc82288cf88
text/template.(*state).walkRange.func1(0x6609e0, 0xc822297a58, 0x82, 0x857be0, 0xc82240ca50, 0x196)
	/usr/local/go/src/text/template/exec.go:310 +0x202 fp=0xc82288d178 sp=0xc82288d0d0
text/template.(*state).walkRange(0xc82288d700, 0x825b00, 0xc822588b40, 0x16, 0xc821fd8240)
	/usr/local/go/src/text/template/exec.go:319 +0x465 fp=0xc82288d378 sp=0xc82288d178
text/template.(*state).walk(0xc82288d700, 0x825b00, 0xc822588b40, 0x16, 0x1a45280, 0xc821fd8240)
	/usr/local/go/src/text/template/exec.go:226 +0x264 fp=0xc82288d4c0 sp=0xc82288d378
text/template.(*state).walk(0xc82288d700, 0x825b00, 0xc822588b40, 0x16, 0x1a45680, 0xc821fccf90)
	/usr/local/go/src/text/template/exec.go:223 +0x6a1 fp=0xc82288d608 sp=0xc82288d4c0
text/template.(*Template).Execute(0xc821fc5a00, 0x1a0cc90, 0xc8238cbc00, 0x825b00, 0xc822588b40, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:178 +0x2a7 fp=0xc82288d748 sp=0xc82288d608
html/template.(*Template).Execute(0xc821fccf30, 0x1a0cc90, 0xc8238cbc00, 0x825b00, 0xc822588b40, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:104 +0x9a fp=0xc82288d798 sp=0xc82288d748
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc820230000, 0x825b00, 0xc822588b40, 0xc821bc6a60, 0x18, 0x1a0cc90, 0xc8238cbc00, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:2053 +0xc2 fp=0xc82288d830 sp=0xc82288d798
github.com/spf13/hugo/hugolib.(*Site).render(0xc820230000, 0xc82281cfa0, 0xc, 0x825b00, 0xc822588b40, 0x1a0cc90, 0xc8238cbc00, 0xc821c0e000, 0x8, 0x8, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:2027 +0x2be fp=0xc82288d910 sp=0xc82288d830
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc820230000, 0xc82281cfa0, 0xc, 0xc822340480, 0x1c, 0x825b00, 0xc822588b40, 0xc821c0e000, 0x8, 0x8, ...)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1954 +0x135 fp=0xc82288dc40 sp=0xc82288d910
github.com/spf13/hugo/hugolib.taxonomyRenderer(0xc820230000, 0xc8226f0c60, 0xc8226f0cc0, 0xc82282f370)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1597 +0x10c1 fp=0xc82288df60 sp=0xc82288dc40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82288df68 sp=0xc82288df60
created by github.com/spf13/hugo/hugolib.(*Site).RenderTaxonomiesLists
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1499 +0x117
``

**Comment by christophermancini** [comment]
I just hit this somehow with my custom theme, any thoughts on how to fix it? I was trying to implement pagination using the base templates for taxonomies.

**Comment by bep** [comment]
This issue should be fixed in Hugo 0.16, be more specific if you still think this is an issue, use http://discuss.gohugo.io/ for questions.

**Comment by christophermancini** [comment]
@bep so, I was able to reproduce it. With v.16, I started implementing the block template functionality. I created a baseof.html file for _default that has a block with the key `content`. For my tag taxonomy, I attempted to have it inherit from the _default/baseof.html template, overwriting the `content` block with the following. Sometimes it builds ok, sometimes it generates the same concurrency error as you.

```go
{{ define "content" }}
  {{ $pag := .Paginate .Data.Pages 100 }}
  {{ range $pag.Pages }}
    {{ .Render "li" }}
  {{ end }}
  <div class="clearfix"></div>
  {{ partial "paginator.html" (dict "pag" $pag) }}
{{ end }}
```

I created a gist of the complete error message, so you could see it. https://gist.github.com/christophermancini/81401bbf2fac5847d9a256a9ceb2a20c

**Comment by bep** [comment]
OK, thanks for the report, the error message looks the same, but it is another issue.

https://github.com/spf13/hugo/issues/2224
