### ISSUE TITLE
windows xp 32bit server error

### ISSUE THREAD

**Issue by futurist** [spf13/hugo#2138]
When run in a windows xp 32bit pc, using command `hugo server`, error below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x62ba2b]

goroutine 59 [running]:
sync/atomic.StoreUint64(0x117e4ae4, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/sync/atomic/asm_386.s:190 +0xb
github.com/spf13/afero.(*InMemoryFile).Open(0x117e4aa0, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/afero/memfile.go:55 +0x73
github.com/spf13/afero.(*MemMapFs).lockfreeOpen(0x116ccb48, 0x118199c0, 0x3, 0x0, 0x0, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:222 +0xfe
github.com/spf13/afero.(*MemMapFs).registerWithParent(0x116ccb48, 0x31826b68, 0x117e4aa0)
        /Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:136 +0x100
github.com/spf13/afero.(*MemMapFs).lockfreeMkdir(0x116ccb48, 0x118199b0, 0x3, 0x1ff, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:170 +0x33e
github.com/spf13/afero.(*MemMapFs).registerWithParent(0x116ccb48, 0x31826b68, 0x117e4a50)
        /Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:131 +0xcb
github.com/spf13/afero.(*MemMapFs).lockfreeMkdir(0x116ccb48, 0x118199a0, 0x8, 0x1ff, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:170 +0x33e
github.com/spf13/afero.(*MemMapFs).registerWithParent(0x116ccb48, 0x31826b68, 0x117e4a00)
```

**Comment by bep** [comment]
Duplicates #1750 and maybe some others.

This is fixed in latest source. A workaround for Hugo 0.15 is ` hugo server --renderToDisk`
