### ISSUE TITLE
panic when having .Get 0 in shortcode without data available

### ISSUE THREAD

**Issue by fnurl** [spf13/hugo#2294]
Running hugo revision `48ebd598a9da395ae1ba39376b35fdd1105472ce` compiled and installed using homebrew (`brew install --build-from-source --HEAD hugo`)

When using a shortcode that refers to `.Get 0` Hugo _sometimes_ panics. An Error with information for debugging would be better.

I am using the same theme for two sites. For one of the sites, Hugo crashes/panics when using the  following shortcode saved in `div.html`. See console output below.

``` html
<div data='{{ .Get 0 }}'>{{ .Inner }}</div>
```

console output

```
$ hugo
Started building site
panic: reflect: call of reflect.Value.Len on zero Value [recovered]
	panic: reflect: call of reflect.Value.Len on zero Value

goroutine 26 [running]:
panic(0x760880, 0xc8204cb080)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
text/template.errRecover(0xc82031b0d8)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:139 +0x2f0
panic(0x760880, 0xc8204cb080)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
reflect.Value.Len(0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:1015 +0xd2
github.com/spf13/hugo/hugolib.(*ShortcodeWithPage).Get(0xc820478400, 0x66b3e0, 0xc8204b1650, 0x0, 0x0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/shortcode.go:69 +0xae
reflect.Value.call(0x7e6580, 0xc820478400, 0x213, 0x86d118, 0x4, 0xc8204cb020, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x7e6580, 0xc820478400, 0x213, 0xc8204cb020, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
text/template.(*state).evalCall(0xc82031b068, 0x7e6580, 0xc820478400, 0x16, 0x7e6580, 0xc820478400, 0x213, 0xf5cda0, 0xc82045a990, 0xc82045a87f, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:641 +0xb39
text/template.(*state).evalField(0xc82031b068, 0x7e6580, 0xc820478400, 0x16, 0xc82045a87f, 0x3, 0xf5cda0, 0xc82045a990, 0xc820437c00, 0x2, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:534 +0x350
text/template.(*state).evalFieldChain(0xc82031b068, 0x7e6580, 0xc820478400, 0x16, 0x7e6580, 0xc820478400, 0x16, 0xf5cda0, 0xc82045a990, 0xc82043d0f0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:505 +0x29d
text/template.(*state).evalFieldNode(0xc82031b068, 0x7e6580, 0xc820478400, 0x16, 0xc82045a990, 0xc820437c00, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:469 +0x1e2
text/template.(*state).evalCommand(0xc82031b068, 0x7e6580, 0xc820478400, 0x16, 0xc82045a960, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:407 +0xa91
text/template.(*state).evalPipeline(0xc82031b068, 0x7e6580, 0xc820478400, 0x16, 0xc820456320, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:385 +0x180
text/template.(*state).walk(0xc82031b068, 0x7e6580, 0xc820478400, 0x16, 0xf5cde8, 0xc82045a9c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:215 +0x135
text/template.(*state).walk(0xc82031b068, 0x7e6580, 0xc820478400, 0x16, 0xf961e0, 0xc82045a900)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*Template).Execute(0xc82044f6c0, 0xf912d0, 0xc82021a000, 0x7e6580, 0xc820478400, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:178 +0x2a7
html/template.(*Template).Execute(0xc82045a8a0, 0xf912d0, 0xc82021a000, 0x7e6580, 0xc820478400, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/html/template/template.go:104 +0x9a
github.com/spf13/hugo/hugolib.renderShortcodeWithPage(0xc82045a8a0, 0xc820478400, 0x0, 0x0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/shortcode.go:562 +0x122
github.com/spf13/hugo/hugolib.renderShortcode(0xc8203221ec, 0x3, 0xc82051ab00, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/shortcode.go:271 +0xab0
github.com/spf13/hugo/hugolib.renderShortcode(0xc8203221b1, 0x3, 0xc820114080, 0x7, 0x8, 0x6583a0, 0xc8200ca660, 0x0, 0x0, 0x1, ...)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/shortcode.go:227 +0x5d0
github.com/spf13/hugo/hugolib.renderShortcodes(0xc8202da330, 0xc8204f4000, 0xf96150, 0xc82020e4b0, 0xc82020e4b0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/shortcode.go:305 +0x214
github.com/spf13/hugo/hugolib.extractAndRenderShortcodes(0xc820322000, 0xbea, 0xc8204f4000, 0xf96150, 0xc82020e4b0, 0x0, 0x0, 0x11, 0x0, 0x0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/shortcode.go:291 +0x290
github.com/spf13/hugo/hugolib.(*Page).ProcessShortcodes(0xc8204f4000, 0xf96150, 0xc82020e4b0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/page.go:942 +0xa2
github.com/spf13/hugo/hugolib.commonConvert(0xc8204f4000, 0xf96150, 0xc82020e4b0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/handler_page.go:113 +0x6f
github.com/spf13/hugo/hugolib.markdownHandler.PageConvert(0x0, 0x0, 0x0, 0xc8204f4000, 0xf96150, 0xc82020e4b0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/handler_page.go:60 +0x51
github.com/spf13/hugo/hugolib.(*markdownHandler).PageConvert(0xc820214260, 0xc8204f4000, 0xf96150, 0xc82020e4b0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:113 +0xde
github.com/spf13/hugo/hugolib.(*MetaHandle).Convert(0xc8200ca140, 0x862ea0, 0xc8204f4000, 0xc820362000, 0xc82028a0c0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/handler_meta.go:77 +0x43d
github.com/spf13/hugo/hugolib.pageConverter(0xc820362000, 0xc82028a120, 0xc82028a0c0, 0xc82051a8c0)
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/site.go:968 +0x108
created by github.com/spf13/hugo/hugolib.(*Site).convertSource
	/private/tmp/hugo-20160720-73964-d564jv/src/github.com/spf13/hugo/hugolib/site.go:901 +0x192
```

Changing the shortcode to 

``` html
<div data='something'>{{ .Inner }}</div>
```

No longer makes Hugo panic:

```
$ hugo
Started building site
0 of 39 drafts rendered
0 future content
0 expired content
11 pages created
0 non-page files copied
0 paginator pages created
8 taggar created
0 kategorier created
in 157 ms
```

**Comment by bep** [comment]
What does your calling code look like when this fails? (the short code usage in the content file) I'm having trouble reproducing thig.

**Comment by fnurl** [comment]
I'm just wrapping a parts of my markdown with a div to use with jQuery UI's accordion menus.

e.g.

{{% div %}}
markdown
{{% /div %}}

The following shortcode also does not work for me in one of my sites.. I'll try to pinpoint it more.

```
<div {{with .Get "class"}} class="{{ . }}"{{ end }}>
  {{ .Inner }}
</div>
```

**Comment by bep** [comment]
What Go version do you compile this with?

**Comment by fnurl** [comment]
The same revision as above. I'll try to test site that reproduces the issue!

**Comment by fnurl** [comment]
Just tried again with revision `eefee59ad7de621617d4ff085cf768aab4b919b1` and still have the issue.

**Comment by fnurl** [comment]
Here is a minimal hugo site with the bug: https://github.com/fnurl/hugotest

**Comment by bep** [comment]
That fails for me, too. Thanks.

**Comment by fnurl** [comment]
It does look different, but .Get 0 in the `div.html` fails as well. Will check out your new commit!

**Comment by bep** [comment]
OK, my fix should cover both bases, but I'll append it to the test case. I should check why Params gets to be nil, but I'm lazy ...
