### ISSUE TITLE
latest version 0.16.0 crashed using with 

### ISSUE THREAD

**Issue by c0b** [spf13/hugo#2379]
Using the latest `0.16.0 June 6th 2016` release together with https://github.com/djuelg/Shapez-Theme ; just created an empty site and first empty page, run `hugo server` crashed:

That theme might have a problem (/cc @djuelg) but I don't think hugo server should crash in any cases; it may report a user friendlier error for theme authors to fix and continue run (or quit depends on how severe the error is)

```console
$ hugo version
Hugo Static Site Generator v0.16 BuildDate: 2016-06-06T05:31:27-07:00
$ hugo server --bind '::' -p 12337
Started building site
panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value [recovered]
	panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
panic(0xb58880, 0xc820335900)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
text/template.errRecover(0xc820324dd0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:139 +0x2f0
panic(0xb58880, 0xc820335900)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
text/template.errRecover(0xc820323778)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:139 +0x2f0
panic(0xb58880, 0xc820335900)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:1671 +0x7b
github.com/spf13/hugo/tpl.in(0xa68b20, 0xc82033c128, 0x0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/tpl/template_funcs.go:400 +0x596
reflect.Value.call(0xb13e60, 0xdf9490, 0x13, 0xc63758, 0x4, 0xc82033c0f0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xb13e60, 0xdf9490, 0x13, 0xc82033c0f0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
text/template.(*state).evalCall(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0xb13e60, 0xdf9490, 0x13, 0x7f7ba665b398, 0xc8202932f0, 0xc82009d220, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:641 +0xb39
text/template.(*state).evalFunction(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0xc820293320, 0x7f7ba665b398, 0xc8202932f0, 0xc8200a62c0, 0x3, 0x4, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:515 +0x336
text/template.(*state).evalCommand(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0xc8202932f0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:412 +0x1e9
text/template.(*state).evalPipeline(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0xc8202639f0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:385 +0x180
text/template.(*state).evalArg(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0x7f7ba66de0a8, 0xa61960, 0x7f7ba66eaa88, 0xc8202639f0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:710 +0x43e
text/template.(*state).evalCall(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0xb13be0, 0xdfa2b8, 0x13, 0x7f7ba665b398, 0xc820293200, 0xc82009d207, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:622 +0x875
text/template.(*state).evalFunction(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0xc820293230, 0x7f7ba665b398, 0xc820293200, 0xc8200a6300, 0x3, 0x4, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:515 +0x336
text/template.(*state).evalCommand(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0xc820293200, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:412 +0x1e9
text/template.(*state).evalPipeline(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0xc820263950, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:385 +0x180
text/template.(*state).walkIfOrWith(0xc820323708, 0xa, 0xc59520, 0xc820521400, 0x16, 0xc820263950, 0xc820293410, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:244 +0xb5
text/template.(*state).walk(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0x7f7ba66eaba8, 0xc8200a6340)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:220 +0x4d9
text/template.(*state).walk(0xc820323708, 0xc59520, 0xc820521400, 0x16, 0x7f7ba669d038, 0xc820292960)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*Template).Execute(0xc82026ffc0, 0x7f7ba66e4480, 0xc8201e9f10, 0xc59520, 0xc820521400, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:178 +0x2a7
html/template.(*Template).Execute(0xc820292900, 0x7f7ba66e4480, 0xc8201e9f10, 0xc59520, 0xc820521400, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/html/template/template.go:104 +0x9a
github.com/spf13/hugo/tpl.executeTemplate(0xc59520, 0xc820521400, 0x7f7ba66e4480, 0xc8201e9f10, 0xc820334540, 0x2, 0x2)
	/Users/spf13/gopath/src/github.com/spf13/hugo/tpl/template.go:129 +0x196
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0xc59520, 0xc820521400, 0xc820334540, 0x2, 0x2, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/tpl/template.go:146 +0xdf
github.com/spf13/hugo/tpl.partial(0xc820188b72, 0xb, 0xc8206ed3b0, 0x1, 0x1, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/tpl/template.go:115 +0x24e
reflect.Value.call(0xb1ada0, 0xdf94e8, 0x13, 0xc63758, 0x4, 0xc8203328d0, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0xb1ada0, 0xdf94e8, 0x13, 0xc8203328a0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
text/template.(*state).evalCall(0xc820324d60, 0xc59520, 0xc82030e010, 0x196, 0xb1ada0, 0xdf94e8, 0x13, 0x7f7ba665b398, 0xc8201908d0, 0xc820188b69, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:641 +0xb39
text/template.(*state).evalFunction(0xc820324d60, 0xc59520, 0xc82030e010, 0x196, 0xc820190900, 0x7f7ba665b398, 0xc8201908d0, 0xc820289880, 0x3, 0x4, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:515 +0x336
text/template.(*state).evalCommand(0xc820324d60, 0xc59520, 0xc82030e010, 0x196, 0xc8201908d0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:412 +0x1e9
text/template.(*state).evalPipeline(0xc820324d60, 0xc59520, 0xc82030e010, 0x196, 0xc8201e7540, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:385 +0x180
text/template.(*state).walk(0xc820324d60, 0xc59520, 0xc82030e010, 0x196, 0x7f7ba66e29a8, 0xc820190930)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:215 +0x135
text/template.(*state).walk(0xc820324d60, 0xc59520, 0xc82030e010, 0x196, 0x7f7ba669d038, 0xc82019fc20)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*state).walkRange.func1(0xa64320, 0xc8206ece50, 0x82, 0xc59520, 0xc82030e010, 0x196)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:310 +0x202
text/template.(*state).walkRange(0xc820324d60, 0xc27a60, 0xc82026c480, 0x16, 0xc8202899c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:319 +0x465
text/template.(*state).walk(0xc820324d60, 0xc27a60, 0xc82026c480, 0x16, 0x7f7ba665b0c0, 0xc8202899c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:226 +0x264
text/template.(*state).walk(0xc820324d60, 0xc27a60, 0xc82026c480, 0x16, 0x7f7ba669d038, 0xc82019f5c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:223 +0x6a1
text/template.(*Template).Execute(0xc820289340, 0x7f7ba66e4480, 0xc8201e9260, 0xc27a60, 0xc82026c480, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:178 +0x2a7
html/template.(*Template).Execute(0xc82019f560, 0x7f7ba66e4480, 0xc8201e9260, 0xc27a60, 0xc82026c480, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/html/template/template.go:104 +0x9a
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc8202c2000, 0xc27a60, 0xc82026c480, 0xc82027b980, 0x18, 0x7f7ba66e4480, 0xc8201e9260, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:2044 +0xc2
github.com/spf13/hugo/hugolib.(*Site).render(0xc8202c2000, 0xc8206ec250, 0x8, 0xc27a60, 0xc82026c480, 0x7f7ba66e4480, 0xc8201e9260, 0xc820310000, 0x14, 0x20, ...)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:2018 +0x2be
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc8202c2000, 0xc8206ec250, 0x8, 0xc8206d8372, 0x0, 0xc27a60, 0xc82026c480, 0xc820310000, 0x14, 0x20, ...)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1938 +0x135
github.com/spf13/hugo/hugolib.(*Site).renderSectionLists(0xc8202c2000, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1655 +0x660
github.com/spf13/hugo/hugolib.(*Site).Render(0xc8202c2000, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:724 +0x104
github.com/spf13/hugo/hugolib.(*Site).Build(0xc8202c2000, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:380 +0x80
github.com/spf13/hugo/commands.buildSite(0xc820325867, 0x1, 0x1, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:688 +0x1b8
github.com/spf13/hugo/commands.build(0xc8203259ae, 0x1, 0x1, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:525 +0x3be
github.com/spf13/hugo/commands.server(0x107e400, 0xc8201c9e40, 0x0, 0x4, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/server.go:163 +0x6f2
github.com/spf13/cobra.(*Command).execute(0x107e400, 0xc8201c9d40, 0x4, 0x4, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/cobra/command.go:561 +0x62c
github.com/spf13/cobra.(*Command).ExecuteC(0x107d000, 0x107e400, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/cobra/command.go:651 +0x55c
github.com/spf13/hugo/commands.Execute()
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:168 +0x77
main.main()
	/Users/spf13/gopath/src/github.com/spf13/hugo/main.go:26 +0x28
```

**Comment by bep** [comment]
A crash is a crash, as to friendlier error messages, we have plenty of issues that duplicates this. Please take questions at the forum.

**Comment by c0b** [comment]
> Please take questions at the forum.

wait, I have searched in [issues list](https://github.com/spf13/hugo/issues) not seeing any similar crash by `panic: reflect: call of reflect.Value.Type on zero Value [recovered]` ; could you mark it as duplicate or another issue? do you have links show ongoing effort to fix the problem? or would blame theme author in this crash log?

**Comment by bep** [comment]
We are understaffed and may not be perfect. This means you will not get me to track down a duplicate of this issue, but trust me, it is there. Please ask any further questions on the forum.
