### ISSUE TITLE
Hugo test fails on 32-bit machine

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2415]
```bash
$ go version
go version go1.7 windows/386
$ go env
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:/go
set GORACE=
set GOROOT=C:\progra\go
set GOTOOLDIR=C:\progra\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
$ go get -d -t -u github.com/spf13/hugo/...
$ go test github.com/spf13/hugo/...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x555dbc]

goroutine 691 [running]:
panic(0x9eb040, 0x115b2030)
        C:/progra/go/src/runtime/panic.go:500 +0x331
text/template.errRecover(0x11681b8c)
        C:/progra/go/src/text/template/exec.go:140 +0xd9
panic(0x9eb040, 0x115b2030)
        C:/progra/go/src/runtime/panic.go:458 +0x40b
sync/atomic.AddUint64(0x116496d4, 0x1, 0x0, 0x11681260, 0x0)
        C:/progra/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/spf13/hugo/hugolib.(*SiteInfo).addToPaginationPageCount(0x11649654, 0x1, 0x0)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:431 +0x3e
github.com/spf13/hugo/hugolib.(*Node).Paginator.func1()
        C:/go/src/github.com/spf13/hugo/hugolib/pagination.go:289 +0x1f7
sync.(*Once).Do(0x115f5c98, 0x116812cc)
        C:/progra/go/src/sync/once.go:44 +0xcf
github.com/spf13/hugo/hugolib.(*Node).Paginator(0x115f5c00, 0xd60b48, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/go/src/github.com/spf13/hugo/hugolib/pagination.go:292 +0xc0
reflect.Value.call(0xa41800, 0x115f5c00, 0x3213, 0xa4eab2, 0x4, 0x119ed4a0, 0x1, 0x1, 0x0, 0x0, ...)
        C:/progra/go/src/reflect/value.go:434 +0xdd7
reflect.Value.Call(0xa41800, 0x115f5c00, 0x3213, 0xd60b48, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/progra/go/src/reflect/value.go:302 +0x8c
text/template.(*state).evalCall(0x11681b50, 0xa41800, 0x115f5c00, 0x16, 0xa41800, 0x115f5c00, 0x3213, 0xd11fe0, 0x1176cd80, 0x11628e0a, ...)
        C:/progra/go/src/text/template/exec.go:658 +0x87d
text/template.(*state).evalField(0x11681b50, 0xa41800, 0x115f5c00, 0x16, 0x11628e0a, 0x9, 0xd11fe0, 0x1176cd80, 0x117b3798, 0x1, ...)
        C:/progra/go/src/text/template/exec.go:549 +0x301
text/template.(*state).evalFieldChain(0x11681b50, 0xa41800, 0x115f5c00, 0x16, 0xa41800, 0x115f5c00, 0x16, 0xd11fe0, 0x1176cd80, 0x117b3790, ...)
        C:/progra/go/src/text/template/exec.go:520 +0x1d4
text/template.(*state).evalFieldNode(0x11681b50, 0xa41800, 0x115f5c00, 0x16, 0x1176cd80, 0x117b3798, 0x1, 0x1, 0x0, 0x0, ...)
        C:/progra/go/src/text/template/exec.go:484 +0x11e
text/template.(*state).evalCommand(0x11681b50, 0xa41800, 0x115f5c00, 0x16, 0x1176cd60, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/progra/go/src/text/template/exec.go:422 +0x810
text/template.(*state).evalPipeline(0x11681b50, 0xa41800, 0x115f5c00, 0x16, 0x11713f80, 0x0, 0x0, 0x0)
        C:/progra/go/src/text/template/exec.go:400 +0x11c
text/template.(*state).walk(0x11681b50, 0xa41800, 0x115f5c00, 0x16, 0xd11e60, 0x1176cda0)
        C:/progra/go/src/text/template/exec.go:226 +0x18a
text/template.(*state).walk(0x11681b50, 0xa41800, 0x115f5c00, 0x16, 0xd120a0, 0x1176cd20)
        C:/progra/go/src/text/template/exec.go:234 +0x523
text/template.(*Template).execute(0x1176ccc0, 0xd0cee0, 0x1183d680, 0xa41800, 0x115f5c00, 0x0, 0x0)
        C:/progra/go/src/text/template/exec.go:189 +0x1e3
text/template.(*Template).Execute(0x1176ccc0, 0xd0cee0, 0x1183d680, 0xa41800, 0x115f5c00, 0x0, 0x0)
        C:/progra/go/src/text/template/exec.go:175 +0x4b
html/template.(*Template).Execute(0x1176cce0, 0xd0cee0, 0x1183d680, 0xa41800, 0x115f5c00, 0x0, 0x0)
        C:/progra/go/src/html/template/template.go:104 +0x7b
github.com/spf13/hugo/hugolib.(*Site).renderThing(0x11649600, 0xa41800, 0x115f5c00, 0xa5f022, 0x12, 0xd0cee0, 0x1183d680, 0x0, 0x0)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:2300 +0x8a
github.com/spf13/hugo/hugolib.(*Site).renderForLayouts(0x11649600, 0x119ed450, 0xc, 0xa41800, 0x115f5c00, 0xd0cee0, 0x1183d680, 0x1188f980, 0x4, 0x4, ...)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:2272 +0x1ae
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0x11649600, 0x119ed450, 0xc, 0x1188fb20, 0x18, 0xa41800, 0x115f5c00, 0x1188f980, 0x4, 0x4, ...)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:2180 +0xf8
github.com/spf13/hugo/hugolib.taxonomyRenderer(0x0, 0x11649600, 0x119a9540, 0x119a9580, 0x1195a030)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:1683 +0x4da
created by github.com/spf13/hugo/hugolib.(*Site).renderTaxonomiesLists
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:1593 +0x116
FAIL    github.com/spf13/hugo/hugolib   13.297s
```

**Comment by bep** [comment]
@MarkDBlackwell I have pushed a fix for this. Could you test it? (a little bit surprised why this happens in test only, there should be plenty of 32 bit users out there)

**Comment by moorereason** [comment]
@bep, are we not testing the x86 platform in Appveyor?

**Comment by bep** [comment]
>are we not testing the x86 platform in Appveyor?

Only 64 bit Windows, I'm afraid.

**Comment by MarkDBlackwell** [comment]
> Could you test it?

With the latest commit, the new output is:
```bash
$ git fetch origin
$ git merge --ff-only origin/master
Updating a00edff..76bf2dc
Fast-forward
 .travis.yml                          |  2 +-
 docs/content/content/multilingual.md |  4 +-
 helpers/content_renderer.go          |  4 +-
 helpers/general.go                   |  5 +++
 hugolib/hugo_sites.go                | 10 +++--
 hugolib/node.go                      |  1 -
 hugolib/shortcode.go                 |  6 +--
 hugolib/shortcode_test.go            | 79 ++++++++++++++++++++----------------
 hugolib/site.go                      |  3 +-
 tpl/template_funcs.go                |  6 +++
 tpl/template_funcs_test.go           |  4 ++
 tpl/template_i18n.go                 | 20 +++++----
 12 files changed, 86 insertions(+), 58 deletions(-)
$ git branch -v
* master  76bf2dc Fix shortcode vs pygments
$ go test github.com/spf13/hugo/...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x55611c]

goroutine 692 [running]:
panic(0x9eb420, 0x115b2030)
        C:/progra/go/src/runtime/panic.go:500 +0x331
text/template.errRecover(0x119e9b8c)
        C:/progra/go/src/text/template/exec.go:140 +0xd9
panic(0x9eb420, 0x115b2030)
        C:/progra/go/src/runtime/panic.go:458 +0x40b
sync/atomic.AddUint64(0x116e8cb4, 0x2, 0x0, 0x119e9260, 0x0)
        C:/progra/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/spf13/hugo/hugolib.(*SiteInfo).addToPaginationPageCount(0x116e8cb4, 0x2, 0x0)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:432 +0x37
github.com/spf13/hugo/hugolib.(*Node).Paginator.func1()
        C:/go/src/github.com/spf13/hugo/hugolib/pagination.go:289 +0x1f7
sync.(*Once).Do(0x11a16178, 0x119e92cc)
        C:/progra/go/src/sync/once.go:44 +0xcf
github.com/spf13/hugo/hugolib.(*Node).Paginator(0x11a160e0, 0xd60b48, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/go/src/github.com/spf13/hugo/hugolib/pagination.go:292 +0xc0
reflect.Value.call(0xa41be0, 0x11a160e0, 0x3213, 0xa4ee8e, 0x4, 0x119a7fc0, 0x1, 0x1, 0x0, 0x0, ...)
        C:/progra/go/src/reflect/value.go:434 +0xdd7
reflect.Value.Call(0xa41be0, 0x11a160e0, 0x3213, 0xd60b48, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/progra/go/src/reflect/value.go:302 +0x8c
text/template.(*state).evalCall(0x119e9b50, 0xa41be0, 0x11a160e0, 0x16, 0xa41be0, 0x11a160e0, 0x3213, 0xd11fe0, 0x117f9ac0, 0x1167cf5a, ...)
        C:/progra/go/src/text/template/exec.go:658 +0x87d
text/template.(*state).evalField(0x119e9b50, 0xa41be0, 0x11a160e0, 0x16, 0x1167cf5a, 0x9, 0xd11fe0, 0x117f9ac0, 0x11656ad8, 0x1, ...)
        C:/progra/go/src/text/template/exec.go:549 +0x301
text/template.(*state).evalFieldChain(0x119e9b50, 0xa41be0, 0x11a160e0, 0x16, 0xa41be0, 0x11a160e0, 0x16, 0xd11fe0, 0x117f9ac0, 0x11656ad0, ...)
        C:/progra/go/src/text/template/exec.go:520 +0x1d4
text/template.(*state).evalFieldNode(0x119e9b50, 0xa41be0, 0x11a160e0, 0x16, 0x117f9ac0, 0x11656ad8, 0x1, 0x1, 0x0, 0x0, ...)
        C:/progra/go/src/text/template/exec.go:484 +0x11e
text/template.(*state).evalCommand(0x119e9b50, 0xa41be0, 0x11a160e0, 0x16, 0x117f9aa0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/progra/go/src/text/template/exec.go:422 +0x810
text/template.(*state).evalPipeline(0x119e9b50, 0xa41be0, 0x11a160e0, 0x16, 0x1180bdd0, 0x0, 0x0, 0x0)
        C:/progra/go/src/text/template/exec.go:400 +0x11c
text/template.(*state).walk(0x119e9b50, 0xa41be0, 0x11a160e0, 0x16, 0xd11e60, 0x117f9ae0)
        C:/progra/go/src/text/template/exec.go:226 +0x18a
text/template.(*state).walk(0x119e9b50, 0xa41be0, 0x11a160e0, 0x16, 0xd120a0, 0x117f9a60)
        C:/progra/go/src/text/template/exec.go:234 +0x523
text/template.(*Template).execute(0x117f9a00, 0xd0cee0, 0x11791260, 0xa41be0, 0x11a160e0, 0x0, 0x0)
        C:/progra/go/src/text/template/exec.go:189 +0x1e3
text/template.(*Template).Execute(0x117f9a00, 0xd0cee0, 0x11791260, 0xa41be0, 0x11a160e0, 0x0, 0x0)
        C:/progra/go/src/text/template/exec.go:175 +0x4b
html/template.(*Template).Execute(0x117f9a20, 0xd0cee0, 0x11791260, 0xa41be0, 0x11a160e0, 0x0, 0x0)
        C:/progra/go/src/html/template/template.go:104 +0x7b
github.com/spf13/hugo/hugolib.(*Site).renderThing(0x116e8c60, 0xa41be0, 0x11a160e0, 0xa5f40c, 0x12, 0xd0cee0, 0x11791260, 0x0, 0x0)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:2301 +0x8a
github.com/spf13/hugo/hugolib.(*Site).renderForLayouts(0x116e8c60, 0x119a7f70, 0xc, 0xa41be0, 0x11a160e0, 0xd0cee0, 0x11791260, 0x1193d940, 0x4, 0x4, ...)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:2273 +0x1ae
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0x116e8c60, 0x119a7f70, 0xc, 0x1193da80, 0x18, 0xa41be0, 0x11a160e0, 0x1193d940, 0x4, 0x4, ...)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:2181 +0xf8
github.com/spf13/hugo/hugolib.taxonomyRenderer(0x0, 0x116e8c60, 0x1193a300, 0x1193a340, 0x119a7de0)
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:1684 +0x4da
created by github.com/spf13/hugo/hugolib.(*Site).renderTaxonomiesLists
        C:/go/src/github.com/spf13/hugo/hugolib/site.go:1594 +0x116
FAIL    github.com/spf13/hugo/hugolib   11.844s
```

**Comment by bep** [comment]
Hmm ... Ok, thanks for the help. Will have to investigate.

**Comment by MarkDBlackwell** [comment]
I volunteer to run the Go language's tests on itself, just to be sure whether this machine's processor meets [sync/atomic's requirements](https://golang.org/pkg/sync/atomic/) as mentioned here:

> On x86-32, the 64-bit functions use instructions unavailable before the Pentium MMX.

I have a flavor of [Pentium MMX](https://en.wikipedia.org/wiki/P5_%28microarchitecture%29), but Pentium evolved over time, so that's conceivably the problem.

I'll report back after I install the [Go compiler tool chain](https://golang.org/doc/install/source) and run [Go's tests](https://golang.org/doc/contribute.html#Testing).

If the sync/atomic tests fail, I might be able to solve this issue by building Golang from source in some special way.

**Comment by moorereason** [comment]
@MarkDBlackwell, no need for all of that Pentium MMX testing.  I've replicated the problem running go-x86 on x64 Windows 7.
