### ISSUE TITLE
New TOML lib's String() fails on menu types

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2439]
When converting YAML metadata to TOML:

```
panic: unsupported value type: map[main:map[weight:1]]

goroutine 1 [running]:
panic(0x5de040, 0xc4202f65b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/pelletier/go-toml.toTomlValue(0x606400, 0xc4202ea270, 0x0, 0xc4202f6560, 0xe)
	/Users/bep/go/src/github.com/pelletier/go-toml/tomltree_conversions.go:67 +0x398
github.com/pelletier/go-toml.(*TomlTree).toToml(0xc4200518c0, 0x0, 0x0, 0x0, 0x0, 0x4, 0x4)
	/Users/bep/go/src/github.com/pelletier/go-toml/tomltree_conversions.go:105 +0x1c1
github.com/pelletier/go-toml.(*TomlTree).String(0xc4200518c0, 0xc420051848, 0x4)
	/Users/bep/go/src/github.com/pelletier/go-toml/tomltree_conversions.go:119 +0x4f
github.com/spf13/hugo/parser.InterfaceToFrontMatter(0x6084a0, 0xc4202ea090, 0xc40000002b, 0xaa3cf, 0xc420051b80, 0x2, 0x2, 0xc4202ea480)
	/Users/bep/go/src/github.com/spf13/hugo/parser/frontmatter.go:101 +0x3ae
github.com/spf13/hugo/hugolib.(*Page).SetSourceMetaData(0xc4201bc500, 0x6084a0, 0xc4202ea090, 0x2b, 0x28, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/hugolib/page.go:985 +0x41
github.com/spf13/hugo/commands.convertContents(0xc40000002b, 0x6a09e2, 0x1)
	/Users/bep/go/src/github.com/spf13/hugo/commands/convert.go:139 +0x76d
github.com/spf13/hugo/commands.glob..func2(0x9b7500, 0xc42025faa0, 0x0, 0x2, 0x0, 0x0)
	/Users/bep/go/src/github.com/spf13/hugo/commands/convert.go:58 +0x5a
github.com/spf13/cobra.(*Command).execute(0x9b7500, 0xc42025f880, 0x2, 0x2, 0x9b7500, 0xc42025f880)
	/Users/bep/go/src/github.com/spf13/cobra/command.go:599 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0x9b81c0, 0x71c080, 0xfb36, 0x9c0d70)
	/Users/bep/go/src/github.com/spf13/cobra/command.go:689 +0x367
github.com/spf13/hugo/commands.Execute()
	/Users/bep/go/src/github.com/spf13/hugo/commands/hugo.go:174 +0x6d
main.main()
	/Users/bep/go/src/github.com/spf13/hugo/main.go:26 +0x32
```

**Comment by bep** [comment]
It also fails on big integers, 6077473420639406657
