### ISSUE TITLE
Getting a "fatal error: unexpected signal during runtime execution" quite often. 

### ISSUE THREAD

**Issue by 7sharp9** [spf13/hugo#2517]
```
 ✘ 7sharp9@DavesMBP  ~/blog   master  hugo -w
Started building site
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x1f7cf0]

goroutine 1 [running]:
runtime.throw(0x957960, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc820db1730 sp=0xc820db1718
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc820db1780 sp=0xc820db1730
sync.(*Pool).Get(0xc80db0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/pool.go:102 +0x40 fp=0xc820db17d0 sp=0xc820db1780
fmt.newPrinter(0xf54080)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:133 +0x27 fp=0xc820db1810 sp=0xc820db17d0
fmt.Sprintln(0xc820db19d8, 0x2, 0x2, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:270 +0x28 fp=0xc820db1860 sp=0xc820db1810
log.(*Logger).Println(0xc8200967d0, 0xc820db19d8, 0x2, 0x2)
	/usr/local/Cellar/go/1.6.2/libexec/src/log/log.go:182 +0x35 fp=0xc820db18a8 sp=0xc820db1860
github.com/spf13/cast.ToIntE(0x668d80, 0xc8202636e8, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/cast/caste.go:153 +0x258 fp=0xc820db1a00 sp=0xc820db18a8
github.com/spf13/cast.ToInt(0x668d80, 0xc8202636e8, 0xf75371fa)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/cast/cast.go:36 +0x2b fp=0xc820db1a30 sp=0xc820db1a00
github.com/spf13/viper.(*Viper).Get(0xc8201261c0, 0x88ea70, 0x8, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/viper/viper.go:510 +0x9ff fp=0xc820db1c40 sp=0xc820db1a30
github.com/spf13/viper.(*Viper).GetInt(0xc8201261c0, 0x88ea70, 0x8, 0xbe840444c7b806cb)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/viper/viper.go:551 +0x35 fp=0xc820db1c80 sp=0xc820db1c40
github.com/spf13/viper.GetInt(0x88ea70, 0x8, 0xbe840444ffffffff)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/viper/viper.go:549 +0x37 fp=0xc820db1ca8 sp=0xc820db1c80
github.com/spf13/hugo/hugolib.resolvePagerSize(0xcaef00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/hugolib/pagination.go:360 +0x53 fp=0xc820db1d30 sp=0xc820db1ca8
github.com/spf13/hugo/hugolib.(*Node).Paginate(0xc8202299e0, 0x83fe00, 0xc820dc5dc0, 0xcaef00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/hugolib/pagination.go:315 +0x5f fp=0xc820db1e50 sp=0xc820db1d30
runtime.call128(0xc8204e6280, 0x82e470, 0xc820bc2f00, 0x3000000048)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:474 +0x51 fp=0xc820db1ed8 sp=0xc820db1e50
reflect.Value.call(0x82e2c0, 0xc8202299e0, 0x1a13, 0x86a810, 0x4, 0xc820c2e000, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d fp=0xc820db2228 sp=0xc820db1ed8
reflect.Value.Call(0x82e2c0, 0xc8202299e0, 0x1a13, 0xc820dcdb40, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1 fp=0xc820db2288 sp=0xc820db2228
text/template.(*state).evalCall(0xc820db3000, 0x82e2c0, 0xc8202299e0, 0x16, 0x82e2c0, 0xc8202299e0, 0x1a13, 0xf5caf8, 0xc82034bdd0, 0xc82036c098, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:641 +0xb39 fp=0xc820db24d0 sp=0xc820db2288
text/template.(*state).evalField(0xc820db3000, 0x82e2c0, 0xc8202299e0, 0x16, 0xc82036c098, 0x8, 0xf5caf8, 0xc82034bdd0, 0xc820352860, 0x2, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:534 +0x350 fp=0xc820db2820 sp=0xc820db24d0
text/template.(*state).evalFieldChain(0xc820db3000, 0x82e2c0, 0xc8202299e0, 0x16, 0x82e2c0, 0xc8202299e0, 0x16, 0xf5caf8, 0xc82034bdd0, 0xc8203488b0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:505 +0x29d fp=0xc820db28d8 sp=0xc820db2820
text/template.(*state).evalFieldNode(0xc820db3000, 0x82e2c0, 0xc8202299e0, 0x16, 0xc82034bdd0, 0xc820352860, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:469 +0x1e2 fp=0xc820db29b8 sp=0xc820db28d8
text/template.(*state).evalCommand(0xc820db3000, 0x82e2c0, 0xc8202299e0, 0x16, 0xc82034bda0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:407 +0xa91 fp=0xc820db2ae0 sp=0xc820db29b8
text/template.(*state).evalPipeline(0xc820db3000, 0x82e2c0, 0xc8202299e0, 0x16, 0xc8203509b0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:385 +0x180 fp=0xc820db2c78 sp=0xc820db2ae0
text/template.(*state).walk(0xc820db3000, 0x82e2c0, 0xc8202299e0, 0x16, 0xf5cb40, 0xc82034be60)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:215 +0x135 fp=0xc820db2dc0 sp=0xc820db2c78
text/template.(*state).walk(0xc820db3000, 0x82e2c0, 0xc8202299e0, 0x16, 0x1d80000, 0xc82034bb60)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:223 +0x6a1 fp=0xc820db2f08 sp=0xc820db2dc0
text/template.(*Template).Execute(0xc82034ee00, 0xf5de50, 0xc82006cd90, 0x82e2c0, 0xc8202299e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/text/template/exec.go:178 +0x2a7 fp=0xc820db3048 sp=0xc820db2f08
html/template.(*Template).Execute(0xc82034bb00, 0xf5de50, 0xc82006cd90, 0x82e2c0, 0xc8202299e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/html/template/template.go:104 +0x9a fp=0xc820db3098 sp=0xc820db3048
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc8202e4000, 0x82e2c0, 0xc8202299e0, 0xc82053e320, 0x18, 0xf5de50, 0xc82006cd90, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/hugolib/site.go:2044 +0xc2 fp=0xc820db3130 sp=0xc820db3098
github.com/spf13/hugo/hugolib.(*Site).render(0xc8202e4000, 0xc820dc6c30, 0xc, 0x82e2c0, 0xc8202299e0, 0xf5de50, 0xc82006cd90, 0xc820768600, 0xa, 0x10, ...)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/hugolib/site.go:2018 +0x2be fp=0xc820db3210 sp=0xc820db3130
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc8202e4000, 0xc820dc6c30, 0xc, 0xc820dc6c10, 0xc, 0x82e2c0, 0xc8202299e0, 0xc820768600, 0xa, 0x10, ...)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/hugolib/site.go:1938 +0x135 fp=0xc820db3548 sp=0xc820db3210
github.com/spf13/hugo/hugolib.(*Site).renderSectionLists(0xc8202e4000, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/hugolib/site.go:1683 +0x12eb fp=0xc820db3878 sp=0xc820db3548
github.com/spf13/hugo/hugolib.(*Site).Render(0xc8202e4000, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/hugolib/site.go:724 +0x104 fp=0xc820db3898 sp=0xc820db3878
github.com/spf13/hugo/hugolib.(*Site).Build(0xc8202e4000, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/hugolib/site.go:380 +0x80 fp=0xc820db3a18 sp=0xc820db3898
github.com/spf13/hugo/commands.buildSite(0xc820db3b07, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/commands/hugo.go:688 +0x1b8 fp=0xc820db3ac8 sp=0xc820db3a18
github.com/spf13/hugo/commands.build(0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/commands/hugo.go:525 +0x3be fp=0xc820db3c08 sp=0xc820db3ac8
github.com/spf13/hugo/commands.glob.func7(0xc89420, 0xc820013840, 0x0, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/commands/hugo.go:119 +0xdd fp=0xc820db3c50 sp=0xc820db3c08
github.com/spf13/cobra.(*Command).execute(0xc89420, 0xc820084070, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/cobra/command.go:568 +0x668 fp=0xc820db3d68 sp=0xc820db3c50
github.com/spf13/cobra.(*Command).ExecuteC(0xc89420, 0xc89420, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/cobra/command.go:658 +0x55c fp=0xc820db3e78 sp=0xc820db3d68
github.com/spf13/hugo/commands.Execute()
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/hugo/commands/hugo.go:168 +0x77 fp=0xc820db3f18 sp=0xc820db3e78
main.main()
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/main.go:26 +0x28 fp=0xc820db3f30 sp=0xc820db3f18
runtime.main()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc820db3f80 sp=0xc820db3f30
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820db3f88 sp=0xc820db3f80

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 4 [select]:
github.com/spf13/viper.(*Viper).WatchConfig.func1.1(0xc820202120, 0xc82025db00, 0x1f, 0xc8201261c0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/viper/viper.go:246 +0x54e
created by github.com/spf13/viper.(*Viper).WatchConfig.func1
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/viper/viper.go:262 +0x203

goroutine 3 [syscall]:
syscall.Syscall6(0x16b, 0x3, 0x0, 0x0, 0xc82027ae70, 0xa, 0xcaf030, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/syscall/asm_darwin_amd64.s:41 +0x5
golang.org/x/sys/unix.kevent(0x3, 0x0, 0x0, 0xc82027ae70, 0xa, 0xcaf030, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:207 +0x7f
golang.org/x/sys/unix.Kevent(0x3, 0x0, 0x0, 0x0, 0xc82027ae70, 0xa, 0xa, 0xcaf030, 0x0, 0x0, ...)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/golang.org/x/sys/unix/syscall_bsd.go:448 +0x94
github.com/fsnotify/fsnotify.read(0x3, 0xc82027ae70, 0xa, 0xa, 0xcaf030, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/fsnotify/fsnotify/kqueue.go:493 +0x8d
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc820202120)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/fsnotify/fsnotify/kqueue.go:284 +0x193
created by github.com/fsnotify/fsnotify.NewWatcher
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/fsnotify/fsnotify/kqueue.go:62 +0x344

goroutine 22 [chan receive]:
github.com/spf13/viper.(*Viper).WatchConfig.func1(0xc8201261c0)
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/viper/viper.go:265 +0x248
created by github.com/spf13/viper.(*Viper).WatchConfig
	/private/tmp/hugo-20160607-37510-1daro23/hugo-0.16/src/github.com/spf13/viper/viper.go:266 +0x35
```

**Comment by bep** [comment]
See https://discuss.gohugo.io/t/hugo-crashes-on-macos-sierra/4101/16
