### ISSUE TITLE
uglyUrls activation throw panic (on 0.18-DEV)

### ISSUE THREAD

**Issue by Blizarre** [spf13/hugo#2734]
Hi,

I need to activate *uglyURLs* for compatibility reasons, but it break the website generation. But `hugo serve -D` works fine.

**Version:**

go version go1.6.2 linux/amd64
Hugo Static Site Generator v0.18-DEV BuildDate: 2016-11-26T11:44:41Z

**Config.toml**

```
baseurl = "http://test.marache.net/"
title = "Simon Marache-Francisco"
languageCode = "en-uk"
theme = "hugo_theme_robust"
uglyURLs = true

[params]
  dateformat = "02/01/2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.
```

**Stack trace**
```
[0] simon-VirtualBox▹ ~/git/marache.net $ hugo -D -v
INFO: 2016/11/26 12:06:22 hugo.go:348: Using config file: /home/simon/git/marache.net/config.toml
WARN: 2016/11/26 12:06:22 hugo.go:477: Unable to find Static Directory: /home/simon/git/marache.net/static/
INFO: 2016/11/26 12:06:22 hugo.go:486: /home/simon/git/marache.net/themes/hugo_theme_robust/static is the only static directory available to sync from
INFO: 2016/11/26 12:06:22 hugo.go:529: syncing static files to /home/simon/git/marache.net/public/
Started building sites ...
WARN: 2016/11/26 12:06:22 template_i18n.go:63: No translation bundle found for default language "en"
INFO: 2016/11/26 12:06:22 site.go:1482: found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
WARN: 2016/11/26 12:06:22 template_i18n.go:45: Translation func for language en not found, use default.
WARN: 2016/11/26 12:06:22 template_i18n.go:45: Translation func for language en not found, use default.
INFO: 2016/11/26 12:06:22 htmlredirect.go:114: Alias "/post/page/1.html" translated to "post/page/1.html"
INFO: 2016/11/26 12:06:22 htmlredirect.go:114: Alias "/page/1.html" translated to "page/1.html"
2016/11/26 12:06:22 mkdir /home/simon/git/marache.net/public/post.html: not a directory
panic: mkdir /home/simon/git/marache.net/public/post.html: not a directory


goroutine 96 [running]:
panic(0xb16740, 0xc820193680)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
log.Panicln(0xc8204e36e8, 0x1, 0x1)
	/usr/lib/go-1.6/src/log/log.go:334 +0xc1
github.com/spf13/afero.WriteReader(0x7fa0ec8196c0, 0x11e7b68, 0xc82033fd40, 0x38, 0x7fa0ec81fec0, 0xc820159d50, 0x7fa0ec81fd48, 0xc82068c690)
	/home/simon/go/src/github.com/spf13/afero/util.go:49 +0x34c
github.com/spf13/hugo/helpers.WriteToDisk(0xc82033fd40, 0x38, 0x7fa0ec81fec0, 0xc820159d50, 0x7fa0ec8196c0, 0x11e7b68, 0x0, 0x0)
	/home/simon/go/src/github.com/spf13/hugo/helpers/path.go:570 +0x64
github.com/spf13/hugo/target.(*PagePub).Publish(0xc820440d80, 0xc82004b000, 0x11, 0x7fa0ec81fec0, 0xc820159d50, 0x0, 0x0)
	/home/simon/go/src/github.com/spf13/hugo/target/page.go:43 +0xd2
github.com/spf13/hugo/hugolib.(*Site).writeDestPage(0xc8201dc780, 0xc82004b000, 0x11, 0x7fa0ec7dfc50, 0xc820440d80, 0x7fa0ec81fec0, 0xc820159d50, 0x0, 0x0)
	/home/simon/go/src/github.com/spf13/hugo/hugolib/site.go:1907 +0x1cd
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc8201dc780, 0xc820201900, 0x5, 0xc82004b000, 0x11, 0xd3afa0, 0xc820550480, 0xc820477300, 0xa, 0x10, ...)
	/home/simon/go/src/github.com/spf13/hugo/hugolib/site.go:1793 +0xd74
github.com/spf13/hugo/hugolib.(*Site).renderPaginator(0xc8201dc780, 0xc820520900, 0x0, 0x0)
	/home/simon/go/src/github.com/spf13/hugo/hugolib/site_render.go:124 +0x962
github.com/spf13/hugo/hugolib.pageRenderer(0xc8201dc780, 0xc820358b40, 0xc820358ae0, 0xc8201c3700)
	/home/simon/go/src/github.com/spf13/hugo/hugolib/site_render.go:79 +0x64d
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
	/home/simon/go/src/github.com/spf13/hugo/hugolib/site_render.go:46 +0x15e
```

**Comment by Blizarre** [comment]
Just to inform that it works fine with the v0.17 binary builds

**Comment by bogem** [comment]
I become another error:
```
Started building sites ...
Error: Error building site: Error(s) rendering pages: open /Users/albert/pravosudieproject/public/yuridicheskim-li…
```

**Comment by bep** [comment]
I can reproduce it myself. Will fix.
