### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by lpar** [spf13/hugo#2929]
Just had a random fatal error running Hugo:

```
% hugo server
Started building sites ...
fatal error: concurrent map read and map write

goroutine 76 [running]:
runtime.throw(0xb15589, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4257518e0 sp=0xc4257518c0
runtime.mapaccess2_faststr(0xa59640, 0xc4202e4f30, 0xc428205f00, 0xd, 0x1202e4d40, 0x1)
	/usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc425751940 sp=0xc4257518e0
github.com/spf13/afero.(*MemMapFs).Chmod(0xc4202e4d20, 0xc428205f00, 0xd, 0xc4000001ff, 0xc4257b89f0, 0x696c2f7367617400)
	/home/meta/go/src/github.com/spf13/afero/memmap.go:316 +0x89 fp=0xc425751990 sp=0xc425751940
github.com/spf13/afero.(*MemMapFs).Mkdir(0xc4202e4d20, 0xc428205f00, 0xe, 0x1ff, 0xc428205ec0, 0x19)
	/home/meta/go/src/github.com/spf13/afero/memmap.go:137 +0x343 fp=0xc425751a18 sp=0xc425751990
github.com/spf13/afero.(*MemMapFs).MkdirAll(0xc4202e4d20, 0xc428205f00, 0xe, 0x1ff, 0xc428205f0e, 0xa)
	/home/meta/go/src/github.com/spf13/afero/memmap.go:143 +0x4b fp=0xc425751a68 sp=0xc425751a18
github.com/spf13/afero.WriteReader(0xe09c80, 0xc4202e4d20, 0xc428205f00, 0x18, 0xdfde40, 0xc4252b35e0, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/afero/util.go:46 +0x1df fp=0xc425751ad0 sp=0xc425751a68
github.com/spf13/hugo/helpers.WriteToDisk(0xc428205f00, 0x18, 0xdfde40, 0xc4252b35e0, 0xe09c80, 0xc4202e4d20, 0x0, 0xc4200101e0)
	/home/meta/go/src/github.com/spf13/hugo/helpers/path.go:570 +0x5d fp=0xc425751b20 sp=0xc425751ad0
github.com/spf13/hugo/target.(*PagePub).Publish(0xc4223b8580, 0xc4271362d0, 0xc, 0xdfde40, 0xc4252b35e0, 0x0, 0x1)
	/home/meta/go/src/github.com/spf13/hugo/target/page.go:47 +0x96 fp=0xc425751b70 sp=0xc425751b20
github.com/spf13/hugo/hugolib.(*Site).writeDestPage(0xc4201ea280, 0xc4271362d0, 0xc, 0x7f4f9813dc50, 0xc4223b8580, 0xdfde40, 0xc4252b35e0, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site.go:1914 +0x15f fp=0xc425751bf8 sp=0xc425751b70
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc4201ea280, 0xafa7ce, 0x5, 0xc4271362d0, 0xc, 0xaf5ee0, 0xc4297c0000, 0xc42d6d7a00, 0x10, 0x10, ...)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site.go:1794 +0x8b2 fp=0xc425751e28 sp=0xc425751bf8
github.com/spf13/hugo/hugolib.pageRenderer(0xc4201ea280, 0xc42523f500, 0xc42523f4a0, 0xc426547240)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:73 +0x3de fp=0xc425751f80 sp=0xc425751e28
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc425751f88 sp=0xc425751f80
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:46 +0x163

goroutine 1 [chan send]:
github.com/spf13/hugo/hugolib.(*Site).renderPages(0xc4201ea280, 0xb0e939, 0x18)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:50 +0x1ce
github.com/spf13/hugo/hugolib.(*Site).render(0xc4201ea280, 0xc4201ea280, 0xc4201ea280)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site.go:827 +0xd8
github.com/spf13/hugo/hugolib.(*HugoSites).render(0xc421719080, 0xc4202bbe00, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/hugo_sites_build.go:186 +0x65
github.com/spf13/hugo/hugolib.(*HugoSites).Build(0xc421719080, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa2e2c0, 0xc4202f8a00)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/hugo_sites_build.go:58 +0x16c
github.com/spf13/hugo/commands.buildSites(0x1, 0x0, 0xc4202f84e0)
	/home/meta/go/src/github.com/spf13/hugo/commands/hugo.go:669 +0xd1
github.com/spf13/hugo/commands.build(0xc425755abe, 0x1, 0x1, 0xc4202f84c0, 0xc4202f84c0)
	/home/meta/go/src/github.com/spf13/hugo/commands/hugo.go:447 +0x99
github.com/spf13/hugo/commands.server(0xe3c580, 0xe621d0, 0x0, 0x0, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/hugo/commands/server.go:164 +0x4f7
github.com/spf13/cobra.(*Command).execute(0xe3c580, 0xe621d0, 0x0, 0x0, 0xe3c580, 0xe621d0)
	/home/meta/go/src/github.com/spf13/cobra/command.go:632 +0x23e
github.com/spf13/cobra.(*Command).ExecuteC(0xe3ae20, 0xb77590, 0xe43f30, 0x1)
	/home/meta/go/src/github.com/spf13/cobra/command.go:722 +0x367
github.com/spf13/hugo/commands.Execute()
	/home/meta/go/src/github.com/spf13/hugo/commands/hugo.go:160 +0x6d
main.main()
	/home/meta/go/src/github.com/spf13/hugo/main.go:26 +0x32

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 20 [syscall]:
syscall.Syscall6(0xe8, 0x5, 0xc420331b84, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
golang.org/x/sys/unix.EpollWait(0x5, 0xc420331b84, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/home/meta/go/src/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1220 +0x77
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc420279020, 0xb76c00, 0xc420279020, 0x0)
	/home/meta/go/src/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x91
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc4202143c0)
	/home/meta/go/src/github.com/fsnotify/fsnotify/inotify.go:192 +0x196
created by github.com/fsnotify/fsnotify.NewWatcher
	/home/meta/go/src/github.com/fsnotify/fsnotify/inotify.go:61 +0x365

goroutine 21 [select]:
github.com/spf13/viper.(*Viper).WatchConfig.func1.1(0xc4202143c0, 0xc4202904e0, 0x28, 0xc42011a0f0)
	/home/meta/go/src/github.com/spf13/viper/viper.go:256 +0x45b
created by github.com/spf13/viper.(*Viper).WatchConfig.func1
	/home/meta/go/src/github.com/spf13/viper/viper.go:272 +0x255

goroutine 35 [chan receive]:
github.com/spf13/viper.(*Viper).WatchConfig.func1(0xc42011a0f0)
	/home/meta/go/src/github.com/spf13/viper/viper.go:275 +0x29a
created by github.com/spf13/viper.(*Viper).WatchConfig
	/home/meta/go/src/github.com/spf13/viper/viper.go:276 +0x3f

goroutine 75 [semacquire]:
sync.runtime_Semacquire(0xc4202e4d28)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*RWMutex).Lock(0xc4202e4d20)
	/usr/local/go/src/sync/rwmutex.go:91 +0x98
github.com/spf13/afero.(*MemMapFs).Create(0xc4202e4d20, 0xc42820c320, 0x1b, 0x1ff, 0x0, 0x0, 0x2)
	/home/meta/go/src/github.com/spf13/afero/memmap.go:52 +0x5d
github.com/spf13/afero.WriteReader(0xe09c80, 0xc4202e4d20, 0xc42820c320, 0x1b, 0xdfde40, 0xc42d45b340, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/afero/util.go:54 +0xbe
github.com/spf13/hugo/helpers.WriteToDisk(0xc42820c320, 0x1b, 0xdfde40, 0xc42d45b340, 0xe09c80, 0xc4202e4d20, 0x0, 0xc4201ea280)
	/home/meta/go/src/github.com/spf13/hugo/helpers/path.go:570 +0x5d
github.com/spf13/hugo/target.(*Filesystem).Publish(0xc426546f50, 0xc4219f0ec0, 0x1a, 0xdfde40, 0xc42d45b340, 0x0, 0x1)
	/home/meta/go/src/github.com/spf13/hugo/target/file.go:52 +0x96
github.com/spf13/hugo/hugolib.(*Site).writeDestFile(0xc4201ea280, 0xc4219f0ec0, 0x1a, 0xdfde40, 0xc42d45b340, 0xc42820c2a0, 0x16)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site.go:1909 +0x16a
github.com/spf13/hugo/hugolib.(*Site).renderAndWriteXML(0xc4201ea280, 0xc4295e3c40, 0xb, 0xc4219f0ec0, 0x1a, 0xaf5ee0, 0xc42d7dc000, 0xc42d7d2e80, 0x7, 0x8, ...)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site.go:1707 +0x45a
github.com/spf13/hugo/hugolib.(*Site).renderRSS(0xc4201ea280, 0xc4295f5680, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:169 +0x400
github.com/spf13/hugo/hugolib.pageRenderer(0xc4201ea280, 0xc42523f500, 0xc42523f4a0, 0xc426547240)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:84 +0x469
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:46 +0x163

goroutine 78 [runnable]:
sync.runtime_Semacquire(0xc4202e4d2c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*RWMutex).RLock(0xc4202e4d20)
	/usr/local/go/src/sync/rwmutex.go:43 +0x5d
github.com/spf13/afero.(*MemMapFs).Mkdir(0xc4202e4d20, 0xc42820c3a0, 0xc, 0x1ff, 0xc42aaf9aa0, 0x4bfbff)
	/home/meta/go/src/github.com/spf13/afero/memmap.go:126 +0x69
github.com/spf13/afero.(*MemMapFs).MkdirAll(0xc4202e4d20, 0xc42820c3a0, 0xc, 0x1ff, 0xc42820c3ac, 0x9)
	/home/meta/go/src/github.com/spf13/afero/memmap.go:143 +0x4b
github.com/spf13/afero.WriteReader(0xe09c80, 0xc4202e4d20, 0xc42820c3a0, 0x15, 0xdfde40, 0xc42d4060e0, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/afero/util.go:46 +0x1df
github.com/spf13/hugo/helpers.WriteToDisk(0xc42820c3a0, 0x15, 0xdfde40, 0xc42d4060e0, 0xe09c80, 0xc4202e4d20, 0x0, 0xc4201ea280)
	/home/meta/go/src/github.com/spf13/hugo/helpers/path.go:570 +0x5d
github.com/spf13/hugo/target.(*Filesystem).Publish(0xc426546f50, 0xc420974f00, 0x14, 0xdfde40, 0xc42d4060e0, 0x0, 0x1)
	/home/meta/go/src/github.com/spf13/hugo/target/file.go:52 +0x96
github.com/spf13/hugo/hugolib.(*Site).writeDestFile(0xc4201ea280, 0xc420974f00, 0x14, 0xdfde40, 0xc42d4060e0, 0xc422ede4e0, 0x16)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site.go:1909 +0x16a
github.com/spf13/hugo/hugolib.(*Site).renderAndWriteXML(0xc4201ea280, 0xc429ba0840, 0x5, 0xc420974f00, 0x14, 0xaf5ee0, 0xc42d789680, 0xc42d7c1900, 0x7, 0x8, ...)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site.go:1707 +0x45a
github.com/spf13/hugo/hugolib.(*Site).renderRSS(0xc4201ea280, 0xc428619200, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:169 +0x400
github.com/spf13/hugo/hugolib.pageRenderer(0xc4201ea280, 0xc42523f500, 0xc42523f4a0, 0xc426547240)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:84 +0x469
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:46 +0x163

goroutine 77 [runnable]:
github.com/spf13/viper.(*Viper).searchMapWithPathPrefixes(0xc42011a0f0, 0xc420290540, 0xc427131850, 0x1, 0x1, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/viper/viper.go:459 +0xbf
github.com/spf13/viper.(*Viper).find(0xc42011a0f0, 0xc427131836, 0x6, 0x6, 0x6)
	/home/meta/go/src/github.com/spf13/viper/viper.go:914 +0x2aa
github.com/spf13/viper.(*Viper).Get(0xc42011a0f0, 0xc427131836, 0x6, 0xc427131836, 0xc420264000)
	/home/meta/go/src/github.com/spf13/viper/viper.go:588 +0x7c
github.com/spf13/viper.Get(0xc427131836, 0x6, 0xc427131836, 0x6)
	/home/meta/go/src/github.com/spf13/viper/viper.go:585 +0x41
github.com/spf13/hugo/helpers.(*Language).Get(0xc4225ee6e0, 0xc427131836, 0x6, 0x1, 0xc42d7956e0)
	/home/meta/go/src/github.com/spf13/hugo/helpers/language.go:133 +0xa5
github.com/spf13/hugo/helpers.(*Language).GetString(0xc4225ee6e0, 0xafbe31, 0x6, 0x8, 0x1)
	/home/meta/go/src/github.com/spf13/hugo/helpers/language.go:104 +0x3f
github.com/spf13/hugo/hugolib.(*Site).renderRSS(0xc4201ea280, 0xc42103ed80, 0x0, 0x0)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:163 +0x23e
github.com/spf13/hugo/hugolib.pageRenderer(0xc4201ea280, 0xc42523f500, 0xc42523f4a0, 0xc426547240)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:84 +0x469
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:46 +0x163

goroutine 74 [chan receive]:
github.com/spf13/hugo/hugolib.errorCollator(0xc42523f4a0, 0xc42523f560)
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site.go:1594 +0x8d
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
	/home/meta/go/src/github.com/spf13/hugo/hugolib/site_render.go:38 +0xbf
```

Like all the best concurrency errors, it's not readily repeatable, but I thought I'd report it in case the backtrace is enough to let you spot the problem.

Hugo Static Site Generator v0.18-DEV BuildDate: 2016-12-15T08:45:43-06:00

**Comment by bep** [comment]
This was fixed in 99e5fc63c2d3536d53aca40296a9fe280ce91a4e
