### ISSUE TITLE
Panic when `markup = "unknown"`: nil pointer dereference

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#863]
While playing with #862 and learning about `markup` variable in the front matter, I tried something random like `markup = "a"` and `markup = "unknown"`, and Hugo v0.13-DEV crashes with a panic:

```
foka@debian:/work/web/mywebsite$ hugo
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x453099]

goroutine 41 [running]:
runtime.panic(0xa166c0, 0xe02d93)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/spf13/hugo/hugolib.(*MetaHandle).Convert(0xc20808a000, 0xa85da0, 0xc208230700, 0xc208108000, 0xc208136ea0)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/handler_meta.go:69 +0x279
github.com/spf13/hugo/hugolib.pageConverter(0xc208108000, 0xc208136f00, 0xc208136ea0, 0xc208151f40)
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:519 +0xfc
created by github.com/spf13/hugo/hugolib.(*Site).CreatePages
	/home/foka/go/src/github.com/spf13/hugo/hugolib/site.go:463 +0x5c8
```

Hugo v0.12 is unaffected as this nifty handler mechanism is new in v0.13-DEV.

I played around a bit and found that I could add a few lines of code to avoid the panic:

```diff
diff --git a/hugolib/handler_meta.go b/hugolib/handler_meta.go
index 1f65f9a..64ec684 100644
--- a/hugolib/handler_meta.go
+++ b/hugolib/handler_meta.go
@@ -66,6 +66,10 @@ func (mh *MetaHandle) Convert(i interface{}, s *Site, results HandleResults) {
 			results <- HandledResult{err: errors.New("file resulted in a nil page")}
 			return
 		}
+		if h == nil {
+			results <- HandledResult{err: errors.New("No handler found"), page: p}
+			return
+		}
 		results <- h.PageConvert(p, s.Tmpl)
 		p.setSummary()
 		p.analyzePage()
```

But this only gives

    CRITICAL: 2015/01/30 Errors rendering pages: No handler found

as an error message with little hint of what the offending file is and of what causes the error.  So, I am leaving this issue to more capable hands.  :-)

**Comment by anthonyfok** [comment]
@bep, you are awesome!  Thank you for the fix!
