### ISSUE TITLE
Livereload panics sometimes

### ISSUE THREAD

**Issue by bep** [spf13/hugo#911]
Will check, but it's reproduceable by doing edits (or touch a file) in a loop for some minutes.

```
panic: runtime error: slice bounds out of range

goroutine 9216 [running]:
bytes.Replace(0xc208a02000, 0x2a93, 0x21029, 0xc2082b5d00, 0x7, 0x8, 0xc2084366c0, 0xb3, 0xc0, 0x1, ...)
	/home/bep/.gvm/gos/go1.4/src/bytes/bytes.go:642 +0x5fa
github.com/spf13/hugo/transform.LiveReloadInject(0xc208a02000, 0x2a93, 0x21029, 0x0, 0x0, 0x0)
	/home/bep/dev/go/src/github.com/spf13/hugo/transform/livereloadinject.go:16 +0x192
github.com/spf13/hugo/transform.(*chain).Apply(0xc208247d50, 0x7f57fd26f660, 0xc2086617a0, 0x7f57fd273800, 0xc208147810, 0x0, 0x0)
	/home/bep/dev/go/src/github.com/spf13/hugo/transform/chain.go:30 +0x187
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc2084181e0, 0xc208616a80, 0x24, 0xc208616a50, 0x29, 0xa7a780, 0xc2085eb800, 0xc208440b80, 0x5, 0x8, ...)
	/home/bep/dev/go/src/github.com/spf13/hugo/hugolib/site.go:1406 +0x58e
github.com/spf13/hugo/hugolib.pageRenderer(0xc2084181e0, 0xc2082418c0, 0xc208241860, 0xc2082f8ba0)
	/home/bep/dev/go/src/github.com/spf13/hugo/hugolib/site.go:923 +0x47e
created by github.com/spf13/hugo/hugolib.(*Site).RenderPages
	/home/bep/dev/go/src/github.com/spf13/hugo/hugolib/site.go:881 +0x124

```

**Comment by bep** [comment]
I have run my edit loop for 30 minutes, no error. 

Will have an open eye on this, but this was issue 911 ... I added a "catch" for this error if it should occur again.

**Comment by bep** [comment]
OK, it fails on my "temporary" branch, which obviously has some crap (have to find that). But the master looks fine.

**Comment by bep** [comment]
I think I see the issue, will have to think about a good fix. Reopen this to fix it.
