### ISSUE TITLE
Pagination panics with 0 pages

### ISSUE THREAD

**Issue by caynan** [spf13/hugo#948]
Hello guys,

I'm trying to build a blog using Hugo, I'm using the latest version of Hugo (brew formula) `v0.14-DEV BuildDate: 2015-02-22T03:09:28-05:00`

I tryied to use the themes [hyde-x](https://github.com/zyro/hyde-x) from @zyro and [casper](https://github.com/vjeantet/hugo-theme-casper) from @vjeantet, both support pagination, and in both of them when I try to run `hugo` I receive the following error:

**EDIT**:
@zyro, just pointed out to me, this error only occurs if your content folder is empty.

I think is a good idea to return a user friendly message instead of the stack trace.

I'd love to help, I'm kind of new to Go, if anyone could point me the direction.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7d1a5]

goroutine 1 [running]:
text/template.errRecover(0xc2080991d8)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:100 +0xbc
text/template.errRecover(0xc208098070)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:100 +0xbc
github.com/spf13/hugo/hugolib.(*pager).HasPrev(0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/hugolib/pagination.go:65 +0x5
reflect.Value.call(0x633980, 0x0, 0x513, 0x663a70, 0x4, 0x99ac48, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x633980, 0x0, 0x513, 0x99ac48, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc208178300, 0x633980, 0x0, 0x16, 0x633980, 0x0, 0x513, 0xa9e450, 0xc2081638f0, 0xc2080bc192, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalField(0xc208178300, 0x633980, 0x0, 0x16, 0xc2080bc192, 0x7, 0xa9e450, 0xc2081638f0, 0xc20802bcb0, 0x1, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:478 +0x34b
text/template.(*state).evalFieldChain(0xc208178300, 0x633980, 0x0, 0x16, 0x633980, 0x0, 0x16, 0xa9e450, 0xc2081638f0, 0xc20802bca0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:449 +0x2ad
text/template.(*state).evalFieldNode(0xc208178300, 0x633980, 0x0, 0x16, 0xc2081638f0, 0xc20802bcb0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:416 +0x1e6
text/template.(*state).evalCommand(0xc208178300, 0x633980, 0x0, 0x16, 0xc2081638c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:354 +0xb39
text/template.(*state).evalPipeline(0xc208178300, 0x633980, 0x0, 0x16, 0xc20802f900, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walkIfOrWith(0xc208178300, 0xa, 0x633980, 0x0, 0x16, 0xc20802f900, 0xc208163920, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:196 +0xa8
text/template.(*state).walk(0xc208178300, 0x633980, 0x0, 0x16, 0xa9ff10, 0xc2080ffcc0)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:172 +0x616
text/template.(*state).walk(0xc208178300, 0x633980, 0x0, 0x16, 0xaa3288, 0xc208163830)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc20800b880, 0xa9e6c8, 0xc208061e30, 0x633980, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc2080fe440, 0xa9e6c8, 0xc208061e30, 0xc20817d0e0, 0x1e, 0x633980, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/tpl.ExecuteTemplate(0x633980, 0x0, 0xc208061e30, 0xc20817d0a0, 0x2, 0x2)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/tpl/template.go:1118 +0x1d6
github.com/spf13/hugo/tpl.ExecuteTemplateToHTML(0x633980, 0x0, 0xc20817d0a0, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/tpl/template.go:1135 +0xaa
github.com/spf13/hugo/tpl.Partial(0xc20806291d, 0xf, 0xc208186050, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/tpl/template.go:1104 +0x260
reflect.Value.call(0x54e9c0, 0x7ab630, 0x13, 0x663a70, 0x4, 0xc20817ae40, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x54e9c0, 0x7ab630, 0x13, 0xc20817ae10, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:296 +0xbc
text/template.(*state).evalCall(0xc20800bd40, 0x6317c0, 0xc2080ec000, 0x16, 0x54e9c0, 0x7ab630, 0x13, 0xaa3318, 0xc2081625a0, 0xc208062914, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:567 +0xaa4
text/template.(*state).evalFunction(0xc20800bd40, 0x6317c0, 0xc2080ec000, 0x16, 0xc2081625d0, 0xaa3318, 0xc2081625a0, 0xc20800af00, 0x3, 0x4, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:459 +0x33b
text/template.(*state).evalCommand(0xc20800bd40, 0x6317c0, 0xc2080ec000, 0x16, 0xc2081625a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:359 +0x210
text/template.(*state).evalPipeline(0xc20800bd40, 0x6317c0, 0xc2080ec000, 0x16, 0xc20802eb40, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:332 +0x1a8
text/template.(*state).walk(0xc20800bd40, 0x6317c0, 0xc2080ec000, 0x16, 0xa9e498, 0xc208162630)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:167 +0x145
text/template.(*state).walk(0xc20800bd40, 0x6317c0, 0xc2080ec000, 0x16, 0xaa3288, 0xc2080f6d80)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:175 +0x862
text/template.(*Template).Execute(0xc20800acc0, 0xa9e6c8, 0xc208061340, 0x6317c0, 0xc2080ec000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/text/template/exec.go:155 +0x3f2
html/template.(*Template).ExecuteTemplate(0xc2080fe440, 0xa9e6c8, 0xc208061340, 0xc20812a620, 0x10, 0x6317c0, 0xc2080ec000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/html/template/template.go:92 +0xc0
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc2080fc000, 0x6317c0, 0xc2080ec000, 0xc20812a620, 0x10, 0xa9e6c8, 0xc208061340, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:1449 +0x210
github.com/spf13/hugo/hugolib.(*Site).render(0xc2080fc000, 0x6a7490, 0x8, 0x6317c0, 0xc2080ec000, 0xc208061340, 0xc208128500, 0x6, 0x8, 0x0, ...)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:1424 +0x2c0
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc2080fc000, 0x6a7490, 0x8, 0x661510, 0x1, 0x6317c0, 0xc2080ec000, 0xc208128500, 0x6, 0x8, ...)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:1387 +0xdf
github.com/spf13/hugo/hugolib.(*Site).RenderHomePage(0xc2080fc000, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:1201 +0x178
github.com/spf13/hugo/hugolib.(*Site).Render(0xc2080fc000, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:395 +0x1a1
github.com/spf13/hugo/hugolib.(*Site).Build(0xc2080fc000, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/hugolib/site.go:244 +0x84
github.com/spf13/hugo/commands.buildSite(0xc208099a27, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/commands/hugo.go:342 +0xd2
github.com/spf13/hugo/commands.build(0xc208099b5e, 0x1, 0x1)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/commands/hugo.go:254 +0x2cb
github.com/spf13/hugo/commands.server(0x98b8e0, 0xc20801e680, 0x0, 0x2)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/commands/server.go:97 +0x58a
github.com/spf13/cobra.(*Command).execute(0x98b8e0, 0xc20801e5c0, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/cobra/command.go:399 +0x38d
github.com/spf13/cobra.(*Command).findAndExecute(0x98ada0, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/cobra/command.go:366 +0xd4
github.com/spf13/cobra.(*Command).Execute(0x98ada0, 0x0, 0x0)
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/cobra/command.go:452 +0xab3
github.com/spf13/hugo/commands.Execute()
	/private/tmp/hugo-Zc2OIW/hugo-0.13/src/github.com/spf13/hugo/commands/hugo.go:64 +0x2f
main.main()
	/private/tmp/hugo-Zc2OIW/hugo-0.13/main.go:24 +0x2f
```

Any ideia on what might be causing this?

Thank you

**Comment by bep** [comment]
See:

https://github.com/spf13/hugo/blob/master/hugolib/pagination.go#L146

I see two options:

1) Do a FATAL log (which bails out of everything) if 0 paginators are created (0 pages)
2) Adjust the logic so a paginator with one empty pager is created in this case
